### ISSUE TITLE
500 Internal Server Error for Auckland Server

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3325] opened 2023-07-28 14:09 UTC
I received a "500 Internal Server Error" on the [stat tracking tool](https://observablehq.com/@jonfroehlich/live-project-sidewalk-stats) this morning. Upon investigation, I found that the Auckland test server is down (Auckland is one of the rare servers that only has a test server and no production server). I'm guessing recent changes messed it up (probably https://github.com/ProjectSidewalk/SidewalkWebpage/pull/3320). CC @misaugstad and @dylanbun.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/1c3195b7-bcf6-49bc-bd98-11b5a9fde467)

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/45e704d9-b3df-4388-af73-531315038890)

**Comment by misaugstad** [comment] 2023-07-28 17:01
This is actually an issue being caused by too many database connections being open (#3316)! Going to close this as part of that issue which is becoming a much higher priority!

**Closed by misaugstad** 2023-07-28 17:01 UTC
Labels: Bug
