### ISSUE TITLE
Tutorial arrows won't disappear in specific cases

### ISSUE THREAD

**Issue by davphan** [ProjectSidewalk/SidewalkWebpage#2912] opened 2022-05-20 20:22 UTC
##### Brief description of problem/feature
During the tutorial, the arrows appear and disappear at the right steps in the tutorial as they should, most of the time. In the specific case that you:
1. Place a marker too far from the spot it's supposed to be in,
2. Delete the marker when prompted, then
3. Place the marker where it's supposed to go, and continue with the tutorial,
the blinking arrow will stay on the marker instead of going away.

The arrows will disappear when new arrows are drawn, so this bug doesn't break the tutorial in any way, but it'd still be nice to figure out why this is happening when it shouldn't be!

##### Steps to reproduce
1. Place maker too far away and delete it
![image](https://user-images.githubusercontent.com/77756028/169597876-66aaa9c1-7376-44a8-be1b-67d1eead3035.png)
2. Place marker in the right spot and continue with the tutorial
![image](https://user-images.githubusercontent.com/77756028/169598053-1ca199b3-3142-41af-a1a1-740c248759b1.png)
3. Pan the camera slightly and the arrow appears on the marker when it shouldn't!
![image](https://user-images.githubusercontent.com/77756028/169597773-fcb0a818-0dbe-4784-a9b1-d0c418e4f720.png)

**Comment by misaugstad** [comment] 2024-01-05 22:53
Closing both as a duplicate of #3318 and because I fixed this issue in PR #3388

**Closed by misaugstad** 2024-01-05 22:53 UTC
