### ISSUE TITLE
Audit 0.5 Miles But Then Neighborhood Progress Shows that I Audited 1.5 Miles

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#418] opened 2016-11-15 19:26 UTC
Something is going wrong here. My mission was to audit 0.5 miles but when I received the 'Mission Complete' screen, the 'Audited in this mission' said that I audited 1.5 miles. 

![image](https://cloud.githubusercontent.com/assets/1621749/20320284/5cacd526-ab3f-11e6-87b1-1b355907bef0.png)

**Comment by jonfroehlich** [comment] 2016-11-15 19:42
Update: I went ahead and did the next mission, where I was credited with auditing 2 miles in the mission (see green part) rather than 0.5 miles.

![image](https://cloud.githubusercontent.com/assets/1621749/20320938/acf67454-ab41-11e6-8db4-b9941affedbd.png)

**Comment by jonfroehlich** [comment] 2016-11-15 20:10
This is also captured in this video: https://youtu.be/EQlLqLZ-aUg

**Comment by jonfroehlich** [comment] 2016-11-15 20:22
I think this should probably be a v2 milestone and not a v3.

**Comment by Soben713** [comment] 2016-11-30 17:23
What really happens is that after you finish your current mission, although the progress bar shows 100% complete, but what the mission message (the text above the progress bar) shows, is about the next mission. So it is possible that your mission was indeed to audit 1.5 miles. This is fixed in PR #452 because I made the modal wider and it covers the status sidebar and there won't be any confusion.

**Comment by jonfroehlich** [comment] 2016-11-30 17:25
My mission was not to audit 1.5 miles. Missions don't go above auditing 0.5 miles I don't think. So, I don't think https://github.com/ProjectSidewalk/SidewalkWebpage/pull/452 will fix this.

**Comment by Soben713** [comment] 2016-11-30 17:56
@jonfroehlich Good point. I'll try to reproduce it.

**Comment by Soben713** [comment] 2016-12-08 16:56
I changed the part of the code that computed the `missionDistance` in `ModalMissionComplet.js` file. This problem should be fixed.

**Closed** 2016-12-09 20:07 UTC
Labels: bug, pull-request-submitted
