### ISSUE TITLE
Need to refer to GSV API documentation on how to avoid serving photospheres to users

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#780] opened 2017-06-28 18:10 UTC
Jumping to a new location during a mission often takes users to a GSV [Photo sphere](https://www.androidcentral.com/photo-sphere) where movement is restricted and users can only pan..  Example: [link](https://www.google.com/maps/@38.8898467,-77.0493612,3a,75y,207.67h,81.45t/data=!3m8!1e1!3m6!1s-BPIGY8q4Gxs%2FWVGjhH1wMRI%2FAAAAAAAAaPM%2FVdjcm1pTvmgsSFCtFF9-TH4XZ_9cATOfQCLIBGAYYCw!2e4!3e11!6s%2F%2Flh6.googleusercontent.com%2F-BPIGY8q4Gxs%2FWVGjhH1wMRI%2FAAAAAAAAaPM%2FVdjcm1pTvmgsSFCtFF9-TH4XZ_9cATOfQCLIBGAYYCw%2Fw203-h100-k-no-pi0-ya85.716354-ro0-fo100%2F!7i8704!8i4352) . 

These are not meant to be audited and can be confusing especially for new users. It may be unintuitive to consider jumping to a new location again. We need to go through the GSV API documentation to see if we can disable getting photosphere panoramas when requesting for a new street.

**Comment by r-holland** [comment] 2017-06-28 18:54
Based on my explorations and speed runs for #718, I can confirm this is a constant issue (lawn in front of monuments, botanical garden area, museum gift shop, small square with fountain, etc.). I agree photo spheres are probably unintuitave for new users, and as jump is not emphasized very much in the tutorial, moving to a new area may be confusing.

If photospheres can be disabled, perhaps we consider disabling them a higher priority. It would certainly address probably the biggest concern I noticed when addressing #718.

**Comment by jonfroehlich** [comment] 2017-06-28 18:56
@r-holland, can you look into this? See if photospheres (and user contributed data in general) can be disabled in a GSV API call.

**Comment by r-holland** [comment] 2017-06-28 18:58
Sure, I'll look into it

**Comment by r-holland** [comment] 2017-06-28 19:25
I just started researching, so I can look for more solutions. However, this fix looks fairly easy:
source: google.maps.StreetViewSource.OUTDOOR

![image](https://user-images.githubusercontent.com/19720010/27656008-789c027a-5c15-11e7-8659-3f37dea3391d.png)
(https://developers.google.com/maps/documentation/javascript/3.exp/reference#StreetViewLocationRequest)

"...search only returns panoramas where it's possible to determine whether they're indoors or outdoors. For example, PhotoSpheres are not returned because it's unknown whether they are indoors or outdoors."

**Comment by manaswis** [comment] 2017-06-28 19:45
This is great @r-holland! Great find! Keep researching to see if this is the best way to do this.

**Comment by jonfroehlich** [comment] 2017-06-28 20:36
Yes, this is great. I think this is the solution. So, I think the best thing would be to try and implement and test this. And now we have two great neighborhoods that can serve as test sites.

This will fix some of the issues you identified but obviously not all of them (e.g., going underground, weird routes).

**Comment by r-holland** [comment] 2017-06-29 18:17
I have been working on the code, and I believe photospheres are blocked now. I've been exploring Waterfront and Monumental Core for a while, and I have yet to be dropped in a photosphere. However, this obviously does not confirm that the changes have worked...perhaps I've just been lucky. Any ideas on how to test conclusively whether my changes disabled photospheres?

**Comment by manaswis** [comment] 2017-06-29 18:24
@r-holland This is related to the issue #668. Jon was auditing the street 26319. You can audit that street using: http://localhost:9000/audit/street/26319

Also, check the pano id that he had posted in the issue. You can jump to that pano by typing: svl.panorama.setPano("<panoid>") in the JS browser console. See if that loads after your changes. However, this part I am not very sure if it will work. The auditing of the above mentioned street should work. Try both.

**Comment by r-holland** [comment] 2017-06-29 18:37
Auditing street 26319 went fine. No troubles there.

When I set the Pano to where Jon was, the 360 selfie photosphere still loaded. However, when I tried to scroll around, it triggered a ton of errors, as the functions for getPanorama that I had changed to block photospheres were being called.

This is the behavior I would expect to result from my changes. If you manually setPano through the JS browser console, the photosphere will load. However, this is the only way to get into a photosphere. All the methods in our code that are tasked with selecting a new area will not choose photospheres.

**Comment by r-holland** [comment] 2017-06-29 18:40
Additionally, unlike Jon, I had the "You are very far from your route...click here to return" message flashing at me. This is because I was on a different route and then manually setPano, unlike Jon who was dropped there. This way, with my new code, even if someone were to manually place themselves in a photosphere, the website would flash at them, telling them to get back out. 

Primarily, the fact that errors were thrown when I tried to pan around in the photosphere shows that my code is working, as panning calls upon one of the getPanorama functions that I modified, which now does not want to render the photosphere.

**Comment by manaswis** [comment] 2017-07-03 12:59
Closed via #789

**Closed by manaswis** 2017-07-03 12:59 UTC
Labels: Priority: Low, pull-request-submitted

**Comment by misaugstad** [comment] 2017-07-10 22:22
Got a photosphere when auditing in Monumental Core. Dropped in the Museum of Natural History, which was nice :)

![photosphere](https://user-images.githubusercontent.com/6518824/28042427-3288d7e2-659b-11e7-83bc-b77e6a84aa62.png)

This came up after refreshing the page. However, I have not been able to reproduce through a bunch of testing just now.

**Comment by jonfroehlich** [comment] 2017-07-11 02:15
How is this possible given @r-holland's code changes?

Also, did you use the 'Feedback' tool to log this in our database so that, for example, Ryan could try and rewalk that exact route? (Incidentally, do we have the ability to do this yet...)
