### ISSUE TITLE
Pano registered as visited despite never being visited

### ISSUE THREAD

**Issue by daotyl000** [ProjectSidewalk/SidewalkWebpage#1891] opened 2019-09-03 21:11 UTC
I had went forward on pano and then I went backwards one pano to check something but the mission ended as if I had went on to view the final pano.

This was the furthest pano I had gone to but it changed the section to the bottom of my current position on the map as green even though I did not go there yet.
![Screen Shot 2019-09-03 at 2 08 54 PM](https://user-images.githubusercontent.com/28814007/64209054-6646c700-ce54-11e9-9938-75cad1ad8f1e.png)

This is where I went to and it was also where I started up again after starting the next mission
![Screen Shot 2019-09-03 at 2 08 02 PM](https://user-images.githubusercontent.com/28814007/64209103-84acc280-ce54-11e9-8f8b-ba88462bbcde.png)

**Comment by misaugstad** [comment] 2019-09-06 20:24
I have been able to reproduce this. It seems like this is happening when you are close to the end of a street. Also going off of remembering how the code works, I think when you are a certain distance from the end of the street segment, it loads the new street segment to show on your next step... But if you step backwards instead of forwards it still seems to be showing you the new street _and_ increasing the mission completion percentage! This happens both mid-mission or at the end of a mission.

In the pictures you will notice both that the mission completion percentage has increased, and the next street has been generated at the intersection.

An example at the end of a mission
![mission-98-before-step](https://user-images.githubusercontent.com/6518824/64458129-61c71c00-d0a9-11e9-8107-49f7c1d66051.png)
![mission-98-after-step](https://user-images.githubusercontent.com/6518824/64458133-62f84900-d0a9-11e9-85b7-7a8106571355.png)

An example mid-mission
![mission-20-before-step](https://user-images.githubusercontent.com/6518824/64458152-6c81b100-d0a9-11e9-8588-c4863ccc7c94.png)
![mission-20-after-step](https://user-images.githubusercontent.com/6518824/64458155-6e4b7480-d0a9-11e9-97dd-92751bdbd5a5.png)

**Comment by misaugstad** [comment] 2020-03-28 20:51
So what we're looking for here is for the next street to still load at the time it is loading, we just don't want to highlight the street as green and update the mission complete percentage until you actually take the step forward. Right now it's _assuming_ you are going to step forward next, which you might not.

**Comment by misaugstad** [comment] 2020-06-02 19:52
closing via #2109

**Closed by misaugstad** 2020-06-02 19:52 UTC
Labels: bug, potential-intern-assignment
