### ISSUE TITLE
The full screen icon on the mini-map should be removed

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1560] opened 2019-03-15 00:18 UTC
![image](https://user-images.githubusercontent.com/2873216/54399784-3b39a280-467d-11e9-97a6-5062f725b87e.png)

The encircled icon does nothing and should be removed. It would cause unnecessary confusion if users click on it and nothing happens.

**Comment by misaugstad** [comment] 2019-03-15 16:42
duplicate of #1221 (adding the wording "full screen" to the original issue to make it easier to search for)

**Closed by misaugstad** 2019-03-15 16:42 UTC
