### ISSUE TITLE
Mouse Cursor Icon Does Not Change to Hand On Pan in Tutorial

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#69] opened 2016-04-14 19:07 UTC
This is on Windows 7 with Chrome.

As you can see, during the tutorial, the mouse cursor does not correctly switch to a hand (which makes the hand animation confusing).

![image](https://cloud.githubusercontent.com/assets/1621749/14540331/81bcf1ca-0252-11e6-81f7-f3b574896d1d.png)

**Comment by kotarohara** [comment] 2016-04-14 23:06
Duplicate of #42 .

**Closed** 2016-05-24 18:22 UTC
Labels: duplicate, Intern Assignment, Priority: Low

**Comment by jonfroehlich** [comment] 2016-05-24 18:44
Yay, we finally fixed this! Nice!
