### ISSUE TITLE
Hover information in validation UI lacks colons

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2638] opened 2021-07-27 18:15 UTC
There should be colons or some other separator after "Tags', "Severity" and "User Description", etc. 

![image](https://user-images.githubusercontent.com/1621749/127206106-eed3323a-7dce-4c91-a7ff-7f77b4608612.png)

**Comment by misaugstad** [comment] 2021-07-28 00:16
duplicate of #2595 

my bad, this was fixed a bit ago, but I've been slacking on getting a new version out on prod!

**Closed by misaugstad** 2021-07-28 00:16 UTC
Labels: EasyFix!, duplicate, ui-bug
