### ISSUE TITLE
Validation mission screen design.

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1555] opened 2019-03-13 13:29 UTC
I think the validation mission screen design could be improved by showing the user examples of the specific label type they are being asked to validate. (Perhaps both positive and negative examples--I'd have to see mocks to know). This would help educate the user and also help prepare them for the validation task.

![image](https://user-images.githubusercontent.com/1621749/54282487-57dcba00-4559-11e9-8d05-170acf62f115.png)

**Comment by misaugstad** [comment] 2019-06-22 00:35
duplicate of #1695

**Closed by misaugstad** 2019-06-22 00:35 UTC
Labels: Validation, duplicate, potential-intern-assignment
