### ISSUE TITLE
Validation Mission "Redo" Button

### ISSUE THREAD

**Issue by devonsnyder** [ProjectSidewalk/SidewalkWebpage#3112] opened 2023-01-24 14:53 UTC
##### Brief description of problem/feature
Would it be possible to create some kind of "redo" or "undo" option for the validation missions that allow users to go back to the previous image? I've heard from a few students were working with that sometimes that click the wrong button and want to correct their validation.

##### Expected behavior
Would allow users to return just to the previous GSV image (couldn't go back through all previously validated images) and re validate that image.

**Comment by jonfroehlich** [comment] 2023-01-24 16:14
This is a duplicate of https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1398.

I'll leave it to Mikey to decide whether to close this one in favor of https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1398.

**Comment by misaugstad** [comment] 2023-01-24 17:51
Closing in favor of #1398!

**Closed by misaugstad** 2023-01-24 17:51 UTC
Labels: Duplicate, Validation

**Comment by devonsnyder** [comment] 2023-01-24 17:52
Great, thanks you two!
