### ISSUE TITLE
It's still hard to determine how much is exactly left in a city to audit

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2952] opened 2022-06-29 16:41 UTC
In trying to bring clarity with how much work is remaining in Oradell, I was examining completion rates in the neighborhood and overall. According to our landing page, we have 54.2% complete with 19.4 miles covered.

![image](https://user-images.githubusercontent.com/1621749/176490461-962d4cf7-a60a-4695-9d85-9b0c1e863540.png)

According to our admin dashboard, we have 26.4 mi covered (74%).
![image](https://user-images.githubusercontent.com/1621749/176490404-3b0fc814-73c8-46c4-b80d-67c926473cf6.png)

I think the landing page is correct and that the admin dashboard is showing all data rather than just high-quality data. If that's the case, I think we should add stats on both (overall, including low and high-quality users) and then the info that is congruent with our landing page and generally how we think about "completion" (which is high quality only)

**Comment by misaugstad** [comment] 2022-07-01 19:03
Sounds good. We can rearrange the table to look something like this:

![Screenshot from 2022-07-01 11-51-01](https://user-images.githubusercontent.com/6518824/176953855-ce783784-fc51-4144-b880-c7f5f3ac4c09.png)

For whoever ends up working on this... We should be able to parameterize the current code to calculate both. When getting the street distance, the code calls `auditedStreetDistance(auditCount: Int, userType: String = "All")`, and it then fills in the `auditTaskQuery` based on the user type. Right after that step, you should be able to add in a filter that removes "low quality" users. I imagine that it would look something like this (assuming you add a boolean parameter called `highQualityOnly`:

```
val highQualityTasks = if (highQualityOnly) {
    for {
        tasks <- auditTaskQuery
        stats <- UserStatTable.userStats if tasks.userId === stats.userId
        if highQuality && !excludeManual
    } yield tasks
} else {
    auditTaskQuery
}
```

**Comment by jonfroehlich** [comment] 2022-07-18 23:19
I'm continuing to be confused by discrepancies in counts. One user in Oradell recently completed 16 miles in the past week; however, our landing page still shows only 19.6 miles covered:

![image](https://user-images.githubusercontent.com/1621749/179632545-b5988868-74a5-4254-ac8a-2a3c593bbf83.png)

In the admin dashboard, I see these counts:
![image](https://user-images.githubusercontent.com/1621749/179632603-7f9f709c-7121-497d-b1cf-c7464f9e0c32.png)

Where Oradell looks nearly 100% complete (if you look at all data collected thus far).

For the user who just completed 16 miles, I don't see anyway of determining if they are inferred as high or low quality:
![image](https://user-images.githubusercontent.com/1621749/179632731-029f9d45-799a-4e02-81d6-f1c9cb8f05ae.png)

Could we add that to the admin user table?

**Comment by jonfroehlich** [comment] 2022-07-18 23:38
OK, I do think that the problem is that the user who just completed 16 more miles (and 24.6 miles total) is marked as low quality by our system. The user id is '2d7e45f5-3656-4aae-9a09-14addfa80d22'. Their labels per meter is 0.037 (according to the [user stats here](https://sidewalk-oradell.cs.washington.edu/v2/userStats?filetype=csv)).

From my analysis, it looks like you need to have at least a labeling rate of 0.04 labels/meter (inclusive) to be marked as high quality. So, this user is just under that threshold.

This is a histogram of users and labels/meter. The pink bar is all users <= 0.04 labels/meter (7 users total)

![image](https://user-images.githubusercontent.com/1621749/179634469-a2a0db4e-02c4-41d3-89fc-a108ae25f6a3.png)

**Comment by misaugstad** [comment] 2022-07-19 00:27
>For the user who just completed 16 miles, I don't see anyway of determining if they are inferred as high or low quality

You're right, this should be added for admins to see somewhere. Either in that table (though it's already overflowing) or on the page for each user that admins can view.

>it looks like you need to have at least a labeling rate of 0.04 labels/meter

It's actually 0.0375 (excluside), or 3.75 labels per 100 meters.

>Interestingly, when trying to validate the new incoming data, my interface says

This seems like the issue we've been dealing with where requests to Google fail and everything gets marked as the imagery having expired. @palbirmin is working on a fix for this right now!

**Comment by jonfroehlich** [comment] 2022-07-19 00:32
Thanks for the detailed notes. Can you manually switch the user of interest to “high quality” once you review them a bit. 

What’s the ticket that @palbirmin is working on? Can you link it here?

**Comment by misaugstad** [comment] 2022-07-19 17:37
>Thanks for the detailed notes. Can you manually switch the user of interest to “high quality” once you review them a bit.

We've been discussing over Slack

>What’s the ticket that @palbirmin is working on? Can you link it here?

I was referring to issue #2458 though I dug a bit deeper today and found that this is not the issue. The issue is that we had temporarily made it so that we aren't given labels from 'low quality' users on the validation page. So you have validated nearly all the labels from high quality users, but have another 1800 or so from users marked as 'low quality' that you could still validate.

The issue where we discuss this and what we want to do going forward is #2721. And I just so happened to have posted a proposal for what to do there about 24 hours ago :joy:

**Comment by misaugstad** [comment] 2022-07-19 17:42
Just added a new ticket for showing user quality on the admin dashboard: #2966

**Closed** 2022-08-02 22:44 UTC
Labels: Admin Interface
