### ISSUE TITLE
Provide users more control over where they audit?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2325] opened 2020-10-16 16:20 UTC
We've gotten this feature request a few times. Essentially, I want to audit streets that I work or live by. How can I do that with your tool. See requests below:

![image](https://user-images.githubusercontent.com/1621749/96283153-9f76c380-0f90-11eb-910f-dc8928c5a9d4.png)

The easiest way to support this would be to allow users to drop a pin on a street/location that they want to audit.

**Comment by misaugstad** [comment] 2020-10-16 19:39
duplicate of #1702 but it took me a long time to find it so I could mark this as a duplicate, so I'll add more useful keywords to the original issue so we can find it in the future

**Closed by misaugstad** 2020-10-16 19:39 UTC
Labels: feature-request
