### ISSUE TITLE
Handling validations by "poor" quality workers

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2702] opened 2021-10-25 17:28 UTC
Related to scheduling/prioritizing re-audits of sections by 'poor' quality workers (https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2698), we also have the issue that people who are struggling with evaluating sidewalk accessibility may also struggle in the role with validating other people's labels (I assume they would though this is an interesting question in itself).

So, we may also need to prioritize additional validations of previously validated labels by those 'poor' quality workers.

**Comment by misaugstad** [comment] 2021-11-10 20:30
duplicate of #2128

**Closed by misaugstad** 2021-11-10 20:30 UTC
Labels: quality-control, Validation
