### ISSUE TITLE
Need landing page for mobile

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2726] opened 2021-11-12 13:01 UTC
Obviously, we haven't put many resources into the mobile version of our site. Currently, when you visit http://projectsidewalk.org, we just throw you into a validation task with no context or landing page. This is confusing to people. See tweet response below.

![image](https://user-images.githubusercontent.com/1621749/141471110-c60a5cc3-276e-4210-9d31-d453598e8aef.png)

So, I suggest we make a simple 'no scroll' landing page for mobile that briefly explains Project Sidewalk, maybe states that laptop has other missions, and then has a call-to-action button to have them validate. Might be nice to then go into a brief tutorial of accessible sidewalk infrastructure with some positive/negative examples of labeling.

**Comment by misaugstad** [comment] 2021-11-20 21:31
duplicate of #1419

I'll copy your suggestions over to that thread though.

**Closed by misaugstad** 2021-11-20 21:31 UTC
Labels: duplicate, Landing Page, Mobile
