### ISSUE TITLE
GSV Navigation Arrows Disappeared and I Can't Move

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1005] opened 2017-08-18 16:09 UTC
Suddenly, my GSV navigation arrows disappeared and I can't move by double clicking on the road. So, I am stuck.

![image](https://user-images.githubusercontent.com/1621749/29467307-944a6d00-8405-11e7-8177-b6b2f00d40eb.png)

Console error:
Error loading depth map for pano UkNj9A8RFPWol_z5VGjLUQ
Could not inflate string
At undefined(undefined)

PanoID: UkNj9A8RFPWol_z5VGjLUQ
```
(svl.taskContainer.getCurrentTask()).getStreetEdgeId();
21219
```

**Comment by manaswis** [comment] 2017-08-18 16:18
Hmm, this is strange. I went to that street and pano. Not able to recreate it. :(

**Comment by jonfroehlich** [comment] 2017-08-18 16:20
Hmm, thanks for checking. Let's keep this issue open and see if it occurs again.

Note that I'm on my parents wifi/ISP, which is very spotty.

**Comment by misaugstad** [comment] 2019-06-22 03:16
Have not reproduced in 2 years so I am going to close it. It looks like a connection issue (judging by the "error loading depth map" bit).

**Closed by misaugstad** 2019-06-22 03:16 UTC
Labels: Priority: Low, bug
