### ISSUE TITLE
Onboarding tutorial: arrow not visible over a curb ramp but appears after refreshing page

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#268] opened 2016-08-30 03:44 UTC
Lee: In the tutorial, it referred to an arrow that was drawn over a curb ramp, but it wasn't visible when I initially loaded the site. I refreshed the page, and then it became visible.

**Comment by manaswis** [comment] 2016-08-30 03:46
I am not very clear about this bug. It was drawn and then it disappeared? When does the arrow show up initially?

**Comment by jonfroehlich** [comment] 2016-08-30 10:57
@manaswis, please follow-up with Lee directly and send him a link to this Issue. He can comment directly to expand.

**Comment by manaswis** [comment] 2016-09-01 04:07
I clarified with Lee. The problem was the tutorial when it loaded, it didn't show the arrow. When he refreshed the page, the yellow arrow showed up.

**Comment by kotarohara** [comment] 2016-09-01 04:47
I am still unclear about this bug. In the first step of the onboarding, example pictures show up in a dialog window. Is Lee saying after clicking OK on that window the arrows don't show up?

/cc @lstearns86

**Comment by lstearns86** [comment] 2016-09-01 05:44
I'm saying that when I first loaded up the tutorial the arrow below was not visible, although the instructions were:

![image](https://cloud.githubusercontent.com/assets/2319490/18156555/00fe857a-6fe5-11e6-891b-19fbdb77707a.png)

I refreshed the page, and after that it seems to have fixed itself (including just now when I went to grab this screenshot). I was using Chrome on Windows 10 at the time, and hadn't created an account yet if any of that makes any difference.

**Comment by kotarohara** [comment] 2016-09-01 12:16
Thank you for the clarification, @lstearns86 !

**Comment by kotarohara** [comment] 2016-09-08 17:30
Can't reproduce this. I'm closing it for now.

**Closed by kotarohara** 2016-09-08 17:30 UTC
Labels: bug
