### ISSUE TITLE
Onboarding "Mission Complete" Error

### ISSUE THREAD

**Issue by mattm401** [ProjectSidewalk/SidewalkWebpage#52] opened 2016-04-12 20:38 UTC
After labeling the 3rd curp ramp and trying to move forward to get a better view of the "washed out" curb ramp, I received the following message:

![image](https://cloud.githubusercontent.com/assets/1121334/14474823/e9fd5324-00cc-11e6-89b8-eca5078bbb9a.png)

I believe this is what Jon was mentioning earlier.

**Comment by mattm401** [comment] 2016-04-12 20:38
After clicking okay, it updated:

![image](https://cloud.githubusercontent.com/assets/1121334/14474857/01dd49b8-00cd-11e6-9a6e-42557809918c.png)

**Comment by mattm401** [comment] 2016-04-12 20:40
Also note: this message needs to be updated as it doesn't read clearly.

**Comment by nguyenist** [comment] 2016-04-13 03:25
@kotarohara @mattm401 

Possible text edit: "Your next mission: Find accessibility points in this neighborhood for the next 500 meters." 

I'm sure you already have a justification for this, but could you use miles? People (I can only speak for those who I conducted walking usability studies, most who grew up in the US) tend to understand feet or miles more than they do meters (unless they do sports: track, football, lacrosse etc.) 

----------------

Related. This is just a suggestion for a future idea. 

Text could perhaps read: "Your next mission: Find accessibility points in this neighborhood [Foggy Bottom, Washington DC] for the next 500 meters." 

Instead of anonymous tagging, it could be fun to let the user know *where* they are actually contributing information. For example, people may feel pride knowing they are helping with accessibility data in DC. I could say, hey I helped map out Shaw, Dupont, Petworth, Capitol Hill, etc. I added the spot (in brackets above) where this could be added.

**Comment by kotarohara** [comment] 2016-04-13 14:16
@nguyenist 

- **Meters -> Feet/Miles:** Yes, I'm planning to change it to feet and miles! 
- **Neighborhood names:** Good idea of including the neighborhood names. The problem is that the GIS data I downloaded from [OpenData DC](http://opendata.dc.gov/datasets/a0225495cda9411db0373a1db40a64d5_21) does not include the neighborhood names. So I currently have not way of showing that... Do you know where I can get that data?

**Comment by jonfroehlich** [comment] 2016-04-13 19:55
I got this error too. First screen in onboard:

![image](https://cloud.githubusercontent.com/assets/1621749/14507328/1b25a2da-0190-11e6-8c25-7d1abceda208.png)

**Comment by kotarohara** [comment] 2016-04-14 23:48
Should be fixed. I'll uploaded the new version tonight.

**Closed** 2016-04-14 23:48 UTC
Labels: bug, Priority: Very High
