### ISSUE TITLE
Labels disappear on mouseover in Safari

### ISSUE THREAD

**Issue by timvng** [ProjectSidewalk/SidewalkWebpage#1783] opened 2019-07-09 20:21 UTC
After placing down a label and not giving it any ratings, if I move the mouse onto the label, it becomes invisible while the description tag still displays. The bug seems to go away if I click on the (invisible) label and give it a rating. Only happens on Safari (I tested on Safari, Firefox, and Chrome).

Screen recording: https://youtu.be/WeWBz_GCVBk

Picture:
<img width="1242" alt="Screen Shot 2019-07-09 at 12 08 46 PM" src="https://user-images.githubusercontent.com/51970755/60919640-2647d700-a24b-11e9-9321-1e1f850459c8.png">

**Comment by misaugstad** [comment] 2020-07-03 23:38
@ThatOneGoat and @shokiami could you both test to see if this bug is still happening on Safari?

**Comment by shokiami** [comment] 2020-07-04 00:44
@misaugstad Just tested it out in Safari and it is still happening. 
Also, it appears that all labels are missing their obstacle icon...

<img width="1040" alt="Screen Shot 2020-07-03 at 5 40 43 PM" src="https://user-images.githubusercontent.com/43970567/86502147-c3e9bf80-bd54-11ea-9b07-e2053ccc7b37.png">

**Comment by misaugstad** [comment] 2020-07-04 00:52
Yikes, okay. Assigning this one to you then @shokiami 

The label not showing up at all is most important, but if you can figure out the other piece right now that would be cool too. If it isn't an easy fix that you find, just create another issue for it please!

**Comment by ThatOneGoat** [comment] 2020-07-04 00:59
Yup, getting the same issue here. I remember running into a similar issue before, and I believe it may be due to something faulty happening with the label visibility toggling

**Comment by shokiami** [comment] 2020-07-14 21:15
I have managed to fix the labels disappearing on mouseover in Safari. However, the icon image and the severity image still do not show up at all in Safari. Specifically, this is caused by an issue with setting image paths (`imageObj.src = imagePath;` in Point.js and `severityImage.src = severityImagePath;` in Label.js).

<img width="1027" alt="Screen Shot 2020-07-14 at 1 50 19 PM" src="https://user-images.githubusercontent.com/43970567/87477043-48053800-c5dc-11ea-88bd-c0c89a0fd647.png">

**Comment by misaugstad** [comment] 2020-07-31 02:22
closing via #2187

**Closed by misaugstad** 2020-07-31 02:22 UTC
Labels: bug
