### ISSUE TITLE
Sign-In Dialog Doesn't Close

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1357] opened 2018-12-01 01:50 UTC
I tried signing in during the tutorial and while the sign-in looks successful, the sign-in dialog won't close.

![image](https://user-images.githubusercontent.com/1621749/49322864-79dd8f80-f4c8-11e8-80e9-a198250bd311.png)

Possibly related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1294

**Comment by misaugstad** [comment] 2018-12-05 23:47
This looks like a duplicate of #1294 

Let me know if there is some difference I am missing.

**Closed by misaugstad** 2018-12-05 23:47 UTC
Labels: bug, duplicate

**Comment by jonfroehlich** [comment] 2018-12-06 00:02
You didn't provide a screenshot :P
