### ISSUE TITLE
Update user dashboard map to show/hide correct, incorrect, and unvalidated labels

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2875] opened 2022-04-23 13:42 UTC
Since @misaugstad has added this functionality to the main LabelMap, we should also add it to the user dashboard.
![image](https://user-images.githubusercontent.com/1621749/164897398-a18847f7-607c-40cc-b7b1-1b811e591070.png)

This is also related to: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/2288, which has been a long-open ticket with a "very high" priority.

**Comment by misaugstad** [comment] 2022-04-26 21:08
closing as a duplicate of #2811

**Closed by misaugstad** 2022-04-26 21:08 UTC
Labels: User Dashboard, User Education
