### ISSUE TITLE
Labels Disappearing in SV Interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#162] opened 2016-07-07 20:39 UTC
I have never seen this bug before. I was just labeling as usual in an intersection and labels started to disappear. Judging by the top-down map (bottom-right corner), the system knows that the labels are there but they are not showing up in the SV interface. Note: I have yet to take a step in this mission, so the problem is not due to me moving.

![image](https://cloud.githubusercontent.com/assets/1621749/16668970/34805cac-4461-11e6-9ce8-b618ae4e7e2a.png)

The log looks like this:
Failed to load resource: the server responded with a status of 404 ()
https://maps.google.com/cbk?output=json&cb_client=maps_sv&v=4&dm=1&pm=1&ph=…defined&callback=jQuery112208157423727181141_1467923195170&_=1467923195171 Failed to load resource: the server responded with a status of 404 ()

![image](https://cloud.githubusercontent.com/assets/1621749/16669021/643e9b8e-4461-11e6-90f1-37075a95a7d9.png)

I'm using Chrome on Windows 10

**Comment by jonfroehlich** [comment] 2016-07-07 20:46
Interesting, if I mouse over where I placed a label, I can see the mouse-over X (see screenshot):

![image](https://cloud.githubusercontent.com/assets/1621749/16669208/3b9c78bc-4462-11e6-92f8-fe931ecfb59a.png)

I can also click on where I think the label should be and it pops up a dialog box:

![image](https://cloud.githubusercontent.com/assets/1621749/16669227/4a45ac58-4462-11e6-96c0-43f445694bda.png)

**Comment by kotarohara** [comment] 2016-07-07 22:38
Actually I'm not sure why this is happening. The error messages were caused by other non-critical bugs (it was querying something unnecessary to Google).

**Comment by jonfroehlich** [comment] 2016-07-07 23:55
Didn't this happen to @danZzyy one time as well? I seem to remember an email about it.

Note that I ended up refreshing the page, so lost my spot in the mission, but refreshing fixed it.

**Comment by kotarohara** [comment] 2016-07-08 00:06
Did all the labels disappear all together? Or did labels appeared/disappeared when you changed the heading angle?

**Comment by jonfroehlich** [comment] 2016-07-08 00:08
I think they disappeared when I changed the heading angle but I can't recall exactly. Once disappeared, they never reappeared.

**Comment by misaugstad** [comment] 2019-06-21 18:50
Has not been reported again for 3 years so I'm going to close this for now :)

**Closed by misaugstad** 2019-06-21 18:50 UTC
Labels: Priority: Low, bug
