### ISSUE TITLE
'Let's take a step' pop-up shows up erratically in the middle of missions and can't dismiss it

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#703] opened 2017-06-20 02:49 UTC
It shows up erratically during missions. 

![image](https://user-images.githubusercontent.com/2873216/27314370-61a8517a-5541-11e7-9f49-e0442cf0f1f6.png)

**Comment by manaswis** [comment] 2017-06-20 02:53
Also, in addition, 'enter' key press doesn't work and hovering over OK, starts blinking the button. Something weird is happening.

**Comment by sagec108** [comment] 2017-06-20 02:56
I think I know why this occurs. I'll try to fix it tonight.

**Comment by sagec108** [comment] 2017-06-20 03:24
So I'm not sure if the "let's take a step" is appearing erratically because of my code. At least from what I've seen, the pop-up shows if the user has no taken a step and spun 360 degrees. For some reason, the pop-up will show after completing a mission and starting a new mission (continuing the previous audit). This may be because we added code to redirect someone to face the route given.

Besides that, I'm not sure how to reproduce the "erratic" pop-up message.

**Comment by manaswis** [comment] 2017-06-20 03:28
> For some reason, the pop-up will show after completing a mission and starting a new mission (continuing the previous audit). 
I also saw this happening. 

> This may be because we added code to redirect someone to face the route given.

You mean positioning the human avatar such that it faces the route?

**Comment by sagec108** [comment] 2017-06-20 03:32
Well positioning the user's view to be facing the route definitely will change the currentHeadingAngle, which likely causes the Let's get started pop-up to appear after completing a mission.

**Comment by manaswis** [comment] 2017-06-20 03:37
Hmm, true. So then we should detect and store that first mission is done. That pop-up code is executed only in the first mission. SInce we load the first mission everytime a user refreshes the page, those messages also show up and triggered.

**Comment by sagec108** [comment] 2017-06-20 03:41
Nevermind, I checked out my code from before I merged recent develop commits into the disable interactions branch. I found the erratic pop-up, so it should be due to something in my code (now unsure what).

**Comment by sagec108** [comment] 2017-06-20 03:51
@manaswis Apparently "trigger("click")" only triggers the event handlers and not the default click behavior, so I changed it. The "Let's take a step" and "check out both sides of the street" pop-ups show when you start a new mission after completing another mission. Can you see if you still get the erratic pop-up with this slight change? I have not been able to reproduce it after this change.

**Comment by manaswis** [comment] 2017-06-20 12:51
Check both sides shows up even after it shown in the previous mission. Can you check if the first mission is detected and completed properly (in Main.js within `startTheMission()`)? Also, see the `handlerPositionUpdate()` within MapService.js. That's where these callbacks to show these messages are triggered.

![image](https://user-images.githubusercontent.com/2873216/27333813-2855eb22-5595-11e7-91df-8bb84e2f2f19.png)

**Comment by manaswis** [comment] 2017-06-20 12:53
Oh I think you mentioned this problem in your comment. Missed it.

>I still need to figure out how to disable the "let's take a step" and "check both sides" pop-ups once the user has finished at least 1 mission (if I press enter these pop-ups will show, clicking will not show them).

**Comment by manaswis** [comment] 2017-06-20 12:57
This is the error I get when I hit enter for the 'Check both sides of the street' message

![image](https://user-images.githubusercontent.com/2873216/27334181-739523b8-5596-11e7-9cb1-1348f87d8155.png)

**Comment by sagec108** [comment] 2017-06-20 14:08
I think the erratic pop-ups and the pop-ups after starting a second mission should be fixed in my latest commit to the branch.

**Closed** 2017-06-21 01:16 UTC
Labels: bug, pull-request-submitted, Relaunch Testing
