### ISSUE TITLE
502 Proxy Error at Seattle Server

### ISSUE THREAD

**Issue by PabloMoret** [ProjectSidewalk/SidewalkWebpage#3239] opened 2023-05-23 15:17 UTC
##### Brief description of problem/feature

There's a persistent API response error when calling [https://sidewalk-sea.cs.washington.edu/adminapi/labels/cvMetadata](https://sidewalk-sea.cs.washington.edu/adminapi/labels/cvMetadata). The server always returns 502 error bad gateway.

Might be caused because of (as Mike said in this [comment](https://github.com/ProjectSidewalk/sidewalk-panorama-tools/issues/25#issuecomment-1520763068)):

- Limit for proxy timeouts
- Not enough Java heap space

##### System info (OS, browser, city, and local/prod/test)

Tested on:

1. Debian GNU/Linux 11 Bullseye (x86_64)
    - Python using requests: Python 3.8.15
    - Brave: 1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit)
    - curl 7.74.0 (x86_64-pc-linux-gnu)
2. Debian GNU/Linux 11 Bullseye (ARM 64bit):
    - curl 7.74.0 (aarch64-unknown-linux-gnu)

##### Expected behavior

Status 200 Ok

##### Current behavior (add screenshots if applicable; check terminal & browser console for errors)

Status Info:
> HTTP/1.1 502 Proxy Error
> Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16
> Content-Type: text/html; charset=iso-8859-1

HTML output:
> Proxy Error
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request [GET /adminapi/labels/cvMetadata](https://sidewalk-sea.cs.washington.edu/adminapi/labels/cvMetadata).
> Reason: Error reading from remote server

##### Steps to reproduce

``curl -I https://sidewalk-sea.cs.washington.edu/adminapi/labels/cvMetadata``

**Comment by misaugstad** [comment] 2023-05-23 17:32
Closing this as a duplicate of #3224 but I will copy some of the info you added over, thank you for being so thorough!

**Comment by PabloMoret** [comment] 2023-05-23 17:34
Sorry, looked for anything containing server or 502 errors but found nothing. Maybe because didn't realize I was filtering open issues or something.

**Closed** 2023-05-23 17:33 UTC

**Comment by misaugstad** [comment] 2023-05-23 17:36
I never used 502 in the issue, which made it hard to search for, which is a big reason why I'm copying some of what you wrote over, thank you again!
