### ISSUE TITLE
Some Street Segments Are Not In The Neighborhood

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#310] opened 2016-09-06 16:21 UTC
I completed another neighborhood on my localhost and uploaded the whole [video on youtube](https://youtu.be/KEnH_rlQLP4). I noticed some missions contain street segments that are far from the neighborhood (look at [5:33](http://www.youtube.com/watch?v=KEnH_rlQLP4&t=5m33s) and [29:33](http://www.youtube.com/watch?v=KEnH_rlQLP4&t=29m33s) for example). It is probably a bug.

Look at this:
![image](https://cloud.githubusercontent.com/assets/1576529/18281943/e7ab9dfa-742c-11e6-8c79-75fe16a38a57.png)

**Comment by jonfroehlich** [comment] 2016-09-06 17:49
Hmm, weird. Definitely a bug. I have not seen this too often. Logan Circle's boundary data looks right so not sure how this could happen or where that bug could be occurring (e.g., why isn't the boundary check working for Logan Circle?).

Keep going through full neighborhoods @Soben713 because have a total lack of data on what happens when you complete a neighborhood and there are lots of probable bugs here (see https://github.com/ProjectSidewalk/SidewalkWebpage/issues/296).

**Comment by kotarohara** [comment] 2016-09-07 16:01
This is a expected behavior. Street segments that **intersect** the neighborhood boundary polygon are served to the users.

**Comment by jonfroehlich** [comment] 2016-09-07 16:04
Ah, got it, so it's just a reflection, in this case, of the small size of this neighborhood and the fact that many segments happened to escape the boundary. I think we can close this then, yah?

**Comment by kotarohara** [comment] 2016-09-07 16:10
Yes, I'm going to close it.

**Closed by kotarohara** 2016-09-07 16:10 UTC
Labels: bug
