### ISSUE TITLE
Uploading Data After Every Step

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#71] opened 2016-04-15 02:01 UTC
My feeling is that we should either:
- upload data after every step
- upload data after every label

Otherwise, if a user does not finish a mission or only audits a few steps, we completely lose that data. That's not good!

**Comment by kotarohara** [comment] 2016-04-20 16:21
This is a duplicate of #44

**Comment by kotarohara** [comment] 2016-05-17 15:17
Jon and I talked. Play around with how frequently (< 30) you we want to submit the data. Once I'm confident that we won't lose significant amount of data, close this issue. #44

**Comment by kotarohara** [comment] 2016-05-20 17:59
I'm closing this. I keep it to 30.

**Closed by kotarohara** 2016-05-20 17:59 UTC
Labels: duplicate, Priority: Low
