### ISSUE TITLE
Validing 'No Sidewalk' labels?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1862] opened 2019-08-12 21:39 UTC
Is this intended behavior? I'm validating 'No Sidewalk' labels in Newberg...

![image](https://user-images.githubusercontent.com/1621749/62900439-fe96d380-bd0e-11e9-948a-5bbfabbe0234.png)

![image](https://user-images.githubusercontent.com/1621749/62900450-03f41e00-bd0f-11e9-8960-516e1809f370.png)

**Comment by misaugstad** [comment] 2019-08-13 00:32
I don't _think_ this is intended behavior..? Although it is possible that you have validated all of the labels placed by other users that are of the main label types, which would cause this. I will look into it this week.

**Comment by jonfroehlich** [comment] 2019-08-13 00:53
Great. Thx.

**Comment by misaugstad** [comment] 2019-08-13 18:51
Got this in Seattle as well. investigating now to see what has changed

**Comment by misaugstad** [comment] 2019-08-13 21:05
closing via #1863

**Closed by misaugstad** 2019-08-13 21:05 UTC
Labels: bug
