### ISSUE TITLE
Got DC label to validate in Seattle (from tutorial?)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1806] opened 2019-07-16 16:58 UTC
![image](https://user-images.githubusercontent.com/1621749/61313940-572a8d80-a7b0-11e9-86f6-c553c47ca2eb.png)

Marked it in Feedback as well.

**Comment by misaugstad** [comment] 2019-07-16 17:44
duplicate of #1636 copying my response from that thread:

>due to the architecture of the website, we need to have the tutorial associated with a street edge id, so I included the DC tutorial street edge in all the databases. To make it so that users did not have to actually audit this street, there is code that would have to be changed/written, and edge cases would have to be dealt with in a few places in the code. I made the determination that this added complexity was not worth it, and that it would be preferable to just have this one street from DC in the database being audited by users. I don't expect your average user to notice.

**Comment by misaugstad** [comment] 2019-09-18 17:28
So I realized that the tutorial street is actually being included in _every_ neighborhood, not just one (which is all that we needed to do). Which means we are getting a lot more DC labels than we need to. Going to fix this shortly. There will still be some DC labels, just not as many.

**Comment by misaugstad** [comment] 2019-09-19 00:17
closing via #1909

**Closed by misaugstad** 2019-09-19 00:17 UTC
Labels: bug, duplicate, wontfix
