### ISSUE TITLE
Really need better general landing page

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1585] opened 2019-03-21 23:07 UTC
Now that we are close to having three active cities, I think it’s really important that the generic landing page (what projectsidewalk.io points to) is improved so that it shows end users all of the cities we are in, provides high level overview of progress, and let’s them choose which city to label. 

I know that the Seattle DOT folks were a bit confused about this and at least one person said that they tried the tool (but it ended up being the DC deployment, which is the old codebase).

**Comment by misaugstad** [comment] 2019-03-21 23:23
duplicate of #1304

**Closed by misaugstad** 2019-03-21 23:23 UTC
Labels: duplicate

**Comment by jonfroehlich** [comment] 2019-03-21 23:36
Haha. But this is intended to bump the Issue. Can you at least humor me and copy over my emphasized call for help to the other thread then :)

**Comment by misaugstad** [comment] 2019-03-21 23:37
Will do :) Also added the "Priority: Medium" tag. And it is unfortunate that you couldn't be at Sidewalk meetings that last 2 weeks to talk to Proshonjit about where he is on the design!
