### ISSUE TITLE
At 100% But Mission Not Complete

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#512] opened 2017-01-15 18:58 UTC
Is this possibly a rounding error?

![image](https://cloud.githubusercontent.com/assets/1621749/21965276/9406767e-db2a-11e6-9d24-7ac2ae2bf40c.png)

Note: Immediately after I took this screenshot, I took a step and the 'Mission Complete' dialog showed (ending the mission).

**Comment by manaswis** [comment] 2017-03-27 19:10
Duplicate of #553. Closing this one as the latest one has more information.

**Closed by manaswis** 2017-03-27 19:10 UTC
Labels: bug, duplicate, Priority: Low
