### ISSUE TITLE
Occasional infinite loop when trying to load the audit screen

### ISSUE THREAD

**Issue by lstrobel** [ProjectSidewalk/SidewalkWebpage#1593] opened 2019-03-26 22:08 UTC
I've been having this odd issue on the develop branch where the audit screen seems to infinitely refresh itself, never to load. It happens on both Chrome and Firefox. I can't get it to happen on our test servers, though. 
![Untitled-2](https://user-images.githubusercontent.com/12887715/55036811-f563cf00-4fd8-11e9-99b7-2fae22229da8.gif)
(The behavior shown in the gif goes on forever)

It happens about 30% of the time I try to go on the audit page.

**Comment by misaugstad** [comment] 2019-03-26 23:44
Duplicate of #1563 

Description of temporary fix is in #1570 along with talk of how to fix it in the long term.

**Closed by misaugstad** 2019-03-26 23:44 UTC
Labels: bug, duplicate
