### ISSUE TITLE
Way to configure showing/hiding label buttons per city

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2869] opened 2022-04-21 18:43 UTC
We currently have the ability to configure **label tags** per city but not **labeling buttons** (e.g., curb ramps, obstacles, pedestrian signals). @misaugstad and I have discussed this quite a bit, especially as we move towards international deployments: each city and country has different urban designs but also different understandings, expectations, and policies about what makes a city accessible.

Liga Peatonal, for example, has suggested that **pedestrian signals** are not relevant in Mexico and asked if we could remove this.

The question for us, however, has been—is the dev cycles worth it to support hiding/showing certain label types per city? In the case of pedestrian signals, you could imagine keeping the button but just tell users not to use it (or they won't use it, since it's not relevant)—which is what we discussed with Liga.

I saw a talk today, however, that has shifted my thinking towards making Project Sidewalk *more* configurable per city/country. I think this quote is relevant—PS was developed with ADA guidelines in mind but it's important that we make appropriate adaptations per deployment context.

![image](https://user-images.githubusercontent.com/1621749/164530482-2a520975-3316-4a96-a6d6-f1f7d8a728bf.png)

**Comment by misaugstad** [comment] 2022-04-21 18:46
:100: Totally agree with this!

**Comment by misaugstad** [comment] 2022-04-29 21:44
closing as a duplicate of #2773

**Closed by misaugstad** 2022-04-29 21:44 UTC
Labels: Duplicate, Internationalization, Explore/Audit
