### ISSUE TITLE
Get access to all streets in our database (audited or not) from API

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2987] opened 2022-08-08 17:07 UTC
In working with PhD student Chu Li, we wondered if we could build a new API backend simply to return all of the streets in our backend database.

The current `/score/streets` API is really neat but only returns `LineString` collections for streets that have been audited. Instead, we want an API call that returns all possible streets. That way, we could potentially build our own street scoring algorithm and not rely on the built-in one from `/score/streets`

**Comment by misaugstad** [comment] 2022-08-08 17:22
closing as duplicate of #2874

**Closed by misaugstad** 2022-08-08 17:22 UTC
Labels: API

**Comment by jonfroehlich** [comment] 2022-08-08 17:23
Hahaha, is my life just now in an endless loop of creating duplicate tickets? Sorry Mikey!

**Comment by misaugstad** [comment] 2022-08-08 17:25
Nah, I'm sure that there are still new ideas to be had. The number of open issues does keep increasing somehow, right? :joy:
