### ISSUE TITLE
When trying to view a contributor, receive an error

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1534] opened 2019-03-08 14:10 UTC
When I click on a username in this table:
![image](https://user-images.githubusercontent.com/1621749/54033331-dfe14f00-4168-11e9-9485-2c5eced5fb99.png)

I get this error:
![image](https://user-images.githubusercontent.com/1621749/54033314-cfc96f80-4168-11e9-9bc5-651156342c31.png)

onError Happened
Execution exception[[IllegalFormatConversionException: f != java.lang.Integer]]

**Comment by misaugstad** [comment] 2019-03-08 17:34
duplicate of #1423 (I've improved the original issue so that it is more easily searchable)

**Closed by misaugstad** 2019-03-08 17:34 UTC
Labels: Admin Interface, bug, duplicate
