### ISSUE TITLE
SPGG Error: Error loading Street View imagery: ZERO_RESULTS

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2666] opened 2021-08-16 21:21 UTC
SPGG won't load:

![image](https://user-images.githubusercontent.com/1621749/129630612-ef071b33-f415-4109-8281-b86316490979.png)

```
audit:1624 Error loading Street View imagery: ZERO_RESULTS
(anonymous) @ audit:1624
audit:1625 Street edge we are trying to audit: 4902
20SVLabel.js:1324 Uncaught TypeError: Cannot read property 'compileSubmissionData' of undefined
    at Tracker.submitForm (SVLabel.js:1324)
    at Tracker.push (SVLabel.js:1315)
    at HTMLDocument.<anonymous> (SVLabel.js:1124)
    at HTMLDocument.dispatch (jquery-1.12.2.min.js:3)
    at HTMLDocument.r.handle (jquery-1.12.2.min.js:3)
```

To replicate, open https://sidewalk-spgg.cs.washington.edu/audit (I did so anonymously) and then click the "Start Exploring" button.

**Comment by jonfroehlich** [comment] 2021-08-16 21:28
![image](https://user-images.githubusercontent.com/1621749/129631744-ace34157-5a90-41bf-ac16-95a880bd66de.png)

**Comment by misaugstad** [comment] 2021-08-18 23:59
duplicate of #2655

**Closed by misaugstad** 2021-08-18 23:59 UTC
Labels: bug, Priority: High
