### ISSUE TITLE
Mission Completion Map Problem After Reloading a Mission

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#324] opened 2016-09-13 15:49 UTC
After reloading a mission, segments that are part of the current mission but were completed before reloading are marked as "previous missions" instead of "this mission" in the completion map (i.e., they are blue instead of green).

This issue is related to #291 because currently there is no clean mechanism to find out what segments/labels are part of the current mission if the page is reloaded.

**Comment by misaugstad** [comment] 2019-01-24 22:04
This should be easier to fix now that the mission infrastructure has been updated in #1319

**Comment by misaugstad** [comment] 2022-06-24 01:14
@zoekaputa here are some step by step reproducing instructions a bit to make this more clear.

1. Go to the /audit page
2. Finish auditing a street as part of a mission. You can tell that you are finishing a street, because the red line you are following ends at some point (image below). Note that once you get close to the end of the street, a new one gets added on, so you'll need to look carefully.
    ![Screenshot from 2022-06-23 18-09-06](https://user-images.githubusercontent.com/6518824/175439982-13e86ad9-a790-49bd-8df9-47d583b5e6d6.png)
3. After you've finished the street and a new one appears, refresh the page. You can see below that I finished auditing one street, and another one has been added (the break is at that intersection you see in the mini map).
    ![Screenshot from 2022-06-23 18-07-13](https://user-images.githubusercontent.com/6518824/175440092-3a5e917b-9dcf-490c-995f-5f440ceb8bef.png)
5. Then continue moving forward until you finish the mission you're on. When looking at the map on the "mission complete" screen, you'll notice that the street that you finished before refreshing the page is shown in blue, when it should be shown in green. In my example below, I refreshed the page after finished the first street, I then finished a second street (which is shown as green), and then I just started a bit of a third street (also in green).
    ![Screenshot from 2022-06-23 18-07-46](https://user-images.githubusercontent.com/6518824/175440236-20f80715-ebb8-44e2-8756-75782c95e73d.png)

The goal is for that blue segment to show up as green, since it was part of the current mission!

**Comment by Z-Setiadi** [comment] 2022-07-01 22:01
Proposed solution plan from after discussing with Mikey:
After doing some investigating I realized that the mission keeps track of a list of tasks (or basically streets) that are worked on during the mission, but this list is never saved to the mission’s data table, so when the page refreshes and the mission object is recreated, the tasks from this list that are completed are not included since they were never saved in the mission data table and are instead in a data table for completed tasks thus being marked as blue (or from a past mission). My overall solution for this would be to have the task to keep track of what mission completed them, so that the recreated mission can know to include them in its list of tasks worked on during the mission.

To implement this solution, I would need to do the following things:
1. Update the database schema (specifically audit_tasks) to include a column that marks what mission the task was completed in.
2. Add code to the backend, for marking a task as complete, that saves what mission the task was completed into the newly created column.
3. Add code to the frontend, for making a mission, that checks to see if any previously completed tasks need to be included in the mission’s list.
4. Add code that saves the current mission's starting point and have front end do calculations that help keep track of how much of a task/street has been completed.

**Comment by misaugstad** [comment] 2022-07-01 22:44
I really love this outline!! You're doing great :) Some things to note:

- As sent over Slack, here is a commit that I think will be a helpful example of how to perform database updates: https://github.com/ProjectSidewalk/SidewalkWebpage/commit/5864d0395fcbb2c807203fd521a3f2ba155eb6d1
- Changes to the database happen in "evolution" files. When a new version is pushed to the server, the "Ups" section of the evolutions files are run; the Ups are run in order, for every evolution that has not already been run on that database. Then if we realize that we need to revert back to an old version of the code that does not include some evolution file, the "Downs" sections is run in reverse order for all the evolutions files that are being removed when we go to an older version. This all ensure that the database updates happen exactly when the code is added to the server, so they are totally in sync :slightly_smiling_face: And the downs are essentially describing how to "undo" the database change.
- The first things you'll need to do is to make the evolutions file. Pull the most recent changes from develop, then make a new evolutions file. I think the most recent one is 155.sql, so you'd be creating 156.sql.
- Then you'll need to update the Scala version of the database schema (AuditTaskTable.scala). This part should be pretty straightforward. You can kinda follow the template from the commit I shared for the evolutions and Scala model files.
- You can start by just initializing everything with null values so that you can get everything to compile. Once you've got the change to the database functioning, you can begin working on the actual fix you outlined :slightly_smiling_face: 
- We've historically stored latitude and longitude in separate columns, but I've been wanting to try out storing them in a single `Geometry:Point` column, so let's try that here! I think when you add the column, you should be able to use the following as part of your query
    ```
    ADD COLUMN <column-name> geometry(Point, 4326)
    ```

>Add code that saves the current mission's starting point and have front end do calculations that help keep track of how much of a task/street has been completed.

I think that the easiest way to do this is probably to add the aforementioned lat/lng point column to the `audit_task` table that defaults to null, we only fill it in if a mission starts in the middle of the street, and it records the starting location for that new mission. If a street is so long that _multiple_ missions start on it, we can wipe the old one and record the new one, since we are only storing this information for the singular purpose of the mission complete screen :)

**Closed** 2022-11-10 01:09 UTC
Labels: Bug, Explore/Audit
