### ISSUE TITLE
Sometimes I click "You've finished this area, click here to take me to..." and it doesn't work

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1191] opened 2017-12-08 17:01 UTC
Sometimes I click "You've finished this area, click here to take me to..." and it doesn't work. Then, afterwards, the "uh, oh, you are far from the route, click here to take you back" message comes up and I click that and *this* works to take me to new area.

**Comment by misaugstad** [comment] 2017-12-08 17:16
Duplicate of #702

**Closed by misaugstad** 2017-12-08 17:16 UTC
Labels: ui-bug

**Comment by jonfroehlich** [comment] 2017-12-08 17:33
Note that #702 describes this as an edge case. However, of the last for 500 ft missions I’ve completed, this has happened twice.

**Comment by misaugstad** [comment] 2017-12-08 17:39
Yeah it definitely isn't an edge case, it happens all the time, I'll change the title
