### ISSUE TITLE
Missing icon for curb ramp and missing curb ramps (control group only)

### ISSUE THREAD

**Issue by crescendochu** [ProjectSidewalk/SidewalkWebpage#3352] opened 2023-08-13 18:17 UTC
##### Brief description of problem/feature
This happened multiple times during our control group pilot study yesterday. Curb ramp and missing curb ramp label types only.
<img width="466" alt="image" src="https://github.com/ProjectSidewalk/SidewalkWebpage/assets/60413478/c282f978-5892-4c9c-8e97-5a477717d304">

**Comment by misaugstad** [comment] 2023-08-13 18:46
What OS and browser was being used? I'm pretty I've seen this for any label type on Chrome in Linux, though the icon will show up again shortly after. Did the icons just never show up?

**Comment by crescendochu** [comment] 2023-08-13 18:58
I think it was Safari with MacOS. Yeah it happened on the second/ third route and never showed up again. So maybe it's a safari thing then? I can add Chrome/ Firefox preferred in the protocol!

**Comment by misaugstad** [comment] 2023-08-13 19:00
Ahh yes. Closing as a duplicate of #3181. Avoiding Safari is probably best... There are a small number of Safari-specific bugs that are hard to test and fix. And that's probably the worst one! Usually a page refresh will do the trick, but just pushing people away from Safari might be easiest.

**Closed by misaugstad** 2023-08-13 19:00 UTC
Labels: Priority High, UI Bug, Prediction Model
