### ISSUE TITLE
Are We Sure that Comments Are Being Saved Correctly?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#204] opened 2016-08-07 19:24 UTC
I thought I entered this bug report before but I could not find it (either in open or closed issues).

I like to add comments to some of my labels; however, I have no way to review these comments. In the admin interface, we do show the "Last 100 Comments" but this appears broken (which is what I thought I previously entered as a bug report). The "Last 100 Comments" has been stuck on showing comments from March and February for a very long time. See below. 

Can we fix this so that we can: (1) verify that comments are indeed being uploaded and saved correctly and (2) easily review recent comments by our users?

![image](https://cloud.githubusercontent.com/assets/1621749/17464682/eb3a0b00-5cb2-11e6-9293-d74e3930304d.png)

**Comment by kotarohara** [comment] 2016-08-08 11:19
This is a duplicate of #189 and it has been fixed. But I haven't pushed it yet.

**Closed by kotarohara** 2016-08-08 11:19 UTC
Labels: bug

**Comment by jonfroehlich** [comment] 2016-08-22 13:18
Have you pushed it now? It looks like the Comments UI in the admin dashboard is still broken. :(

![image](https://cloud.githubusercontent.com/assets/1621749/17855977/5a2a8372-6849-11e6-8156-3c65efe811d6.png)

**Comment by kotarohara** [comment] 2016-08-22 16:03
Yes, you can add a comment and should show up on the admin page.

![project_sidewalk](https://cloud.githubusercontent.com/assets/612263/17861779/6e767626-6860-11e6-8368-7fb13ba6fe8c.png)

**Comment by jonfroehlich** [comment] 2016-08-22 16:21
Great!

![image](https://cloud.githubusercontent.com/assets/1621749/17862368/ebd7a64c-6862-11e6-8204-f590fdb7b5b9.png)
