### ISSUE TITLE
Just Logged On, Got New Mission (4.5 Miles!) But Progress Bar Already Says 9.5% Complete

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#195] opened 2016-07-20 17:54 UTC
I guess I must still not understand how we are doing missions. If I'm told that my mission is to audit 4.5 miles, I expect to have to walk 4.5 miles in the mission and that the mission tracker should start with 0% (to correspond to having walked 0 miles), then when I walk 1 mile, the mission tracker should say ~22%, and then 2 miles, the mission tracker should say 44%, etc.  If this is *not* how missions work and the mission tracker works, why not? If it is how it works, then why do I see this when I first login (note the mission tracker is already at 9%):

![image](https://cloud.githubusercontent.com/assets/1621749/16996877/1ed6b688-4e81-11e6-951e-0a18b362ec71.png)

**Comment by kotarohara** [comment] 2016-07-20 18:32
This is a duplicate of previous issue. I'll tie it back to the existing open issue when I get a chance, which is probably after Aug 1st.

**Comment by jonfroehlich** [comment] 2016-08-22 16:41
@kotarohara, what's the status of this? Have you fixed this yet and is the fix on the deployment server? I just logged in and saw that my mission bar was immediately at 49%--is this because we now save state. That is, if you leave before completing a mission, the backend automatically saves where you left off and you start at that point the next time you log in? Or what's going on?

![image](https://cloud.githubusercontent.com/assets/1621749/17862987/bc0f0cfe-6865-11e6-8131-10c7d3100ff5.png)

**Comment by jonfroehlich** [comment] 2016-08-22 17:24
Here's another screenshot (note that the progress bar in the background is already 49%):

![image](https://cloud.githubusercontent.com/assets/1621749/17864343/b2b361c2-686b-11e6-93df-2b110d4dd896.png)

**Comment by jonfroehlich** [comment] 2016-08-24 16:55
I said:

> @kotarohara, what's the status of this? Have you fixed this yet and is the fix on the deployment server? I just logged in and saw that my mission bar was immediately at 49%--is this because we now save state. That is, if you leave before completing a mission, the backend automatically saves where you left off and you start at that point the next time you log in? Or what's going on?

And Kotaro told me in a meeting that this is exactly what happens.

So, I think the actual fix here for this particular thing is that the Mission Dialog when you first login and return to the mission should be different than the initial Mission Dialog--that is, the Mission Dialog should say something like "Welcome back! You have XXX feet to go to complete this mission" or something.

**Comment by kotarohara** [comment] 2016-09-02 21:25
I moved the last comment to #163 . I'm closing this issue that is actually not an issue.

**Closed by kotarohara** 2016-09-02 21:25 UTC
Labels: bug, ui-update
