### ISSUE TITLE
Signing out doesn't work properly from any other page than audit page

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#1026] opened 2017-08-31 08:15 UTC
I tried this a couple of times. I was logged into my account. I signed out from the landing page and then I clicked Start Mapping. It was signed-in as my account and the audit page was shown accordingly. That was true even when I clicked "See Results": 
![image](https://user-images.githubusercontent.com/2873216/29913170-31956cbc-8de9-11e7-83f7-2eca95a86e38.png)

The webpage activity table shows this well. Notice the user_ids (removed full user id for security purposes):

![image](https://user-images.githubusercontent.com/2873216/29913302-a3908d60-8de9-11e7-89a4-a8cd09b7f151.png)

`977` is an anonymous user and `ee5` is the signed in user

**Comment by lstrobel** [comment] 2018-12-18 23:39
@misaugstad 

I can't seem to replicate this bug. Signing out on the landing page then opening the audit page keeps me signed out. My `webpage_activity` log reflects this as well.

**Comment by jonfroehlich** [comment] 2018-12-19 15:01
Hrm. Maybe we could have another person quickly test this. @paarig, would you mind a quick look at this? Should take like ~5 mins.

**Comment by misaugstad** [comment] 2018-12-19 19:42
@lstrobel keep trying a bunch of different combinations of pages (/audit, landing, /results) trying to sign in/out on the different pages. I'm not sure if there is a way to get this behavior 100% of the time, but sometimes signing in doesn't work and sometimes signing out doesn't work. Just keep trying to break it by signing in and out, I was just able to reproduce on my local environment, develop branch.

**Comment by lstrobel** [comment] 2018-12-20 21:36
@misaugstad 

So I did a pretty comprehensive test while in my local environment on the `develop` branch, here are my results:

(The first row is the page I signed out on, and the first column is the page I visited)

| Page | Landing | `/audit` | `/results` | `/labelingGuide` | `/about`|
|------------------|---------|----------|--------------|--------------------|----------|
| Landing | n/a | Works | Works | Works | Works |
| `/audit` | Works | n/a | * | * | * |
| `/results` | Works | Works | n/a | * | * |
| `/labelingGuide` | Works | Works | * | n/a | * |
| `/about` | Works | Works | * | * | n/a |

\*Signing out from this page redirected me to the landing every time

Do you have any other ideas for how I could replicate this behavior? I can't seem to manage it.

**Comment by jonfroehlich** [comment] 2018-12-28 01:30
Thanks for this @lstrobel. Perhaps @manaswis could try again herself since she's the originally one who posted the problem.

**Comment by misaugstad** [comment] 2018-12-28 03:43
@lstrobel I have been able to recreate a few times now (both on my local machine on the `develop` branch, as well as at http://sidewalk-test.cs.washington.edu) by signing in on the landing page, clicking on "See Results", then signing out there. It doesn't always happen the first time I do it, but it at least ends up happening after I do it a few times.

**Comment by lstrobel** [comment] 2018-12-28 03:58
@misaugstad I just did some more fiddling around. Still completely unable to replicate the bug (after dozens of tries) on Firefox. However, I thought that it could maybe be browser-specific, so I tried Chrome. Lo-and-behold, it happened first try. To be completely honest, I have no idea how to even approach a bug like this that only appears in one browser...

**Comment by misaugstad** [comment] 2018-12-31 22:06
And nice job figuring out that it is Chrome-specific! It helps narrow down the problem :) and agreed with what @jonfroehlich said on figuring out the problem.

**Comment by misaugstad** [comment] 2019-01-16 23:48
Thanks for all the hard work on this @lstrobel !

@jonfroehlich how do you feel about just trying to add the `Thread.sleep` call to see if it fixes it? It definitely isn't good coding practice, but if it fixes the bug for now, maybe we just use it and add a comment saying why we are doing it that links to this issue thread?

**Comment by jonfroehlich** [comment] 2019-01-17 13:55
I assume `Thread.sleep(20)` is 20 milliseconds? :) 

If so, I agree with you @misaugstad. Super kludgey fix but let's implement it, comment it with a link back to this Issue.

Also, my compliments to @lstrobel for digging down into this bug, trying to identify a problem, and coming up with a possible solution.

**Comment by misaugstad** [comment] 2019-01-22 23:54
The fix isn't elegant, but it does seem to work! Fixed in #1402

**Closed by misaugstad** 2019-01-22 23:54 UTC
Labels: Priority: Low, bug, potential-intern-assignment, pull-request-submitted

**Comment by misaugstad** [comment] 2025-07-03 00:08
I've removed our weird fix in PR #3894. Since we've upgraded all of our back end libraries to the newest versions, I'm hoping that we no longer need this hacky fix. I suppose that we'll see if this continues to be an issue 7 years later!
