### ISSUE TITLE
Jumping increases the mission progress significantly

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#315] opened 2016-09-07 18:40 UTC
From PR #312: 
The first option ("I want to explore another area") increases the mission progress gradually (~1%) and sometimes reduces too.
[https://youtu.be/60rdcNztxGc?t=7s](https://youtu.be/60rdcNztxGc?t=7s)

The second option ("I cannot go the direction..") increases the mission progress significantly! It becomes 18% to 49 % to 100%.
See video (starts at 36s): 
[https://youtu.be/60rdcNztxGc?t=36s](https://youtu.be/60rdcNztxGc?t=36s)

Jon's comments:

- When choosing the first option, I agree that the progress bar probably should not increase. What's likely happening is that the current location that you are standing in when you click jump to another area, is being marked as audited. Thus, you are slowly, one GSV location at a time, auditing that neighborhood

- For the second option, I don't think this is a bug. As soon as you say 'I cannot go in the direction that you want me to walk," we have to mark that segment as unauditable/unwalkable, so your mission progress jumps as a result (I'm not sure if @kotarohara  does this by subtracting out the unauditable areas or by simply giving you credit for walking what you cannot walk). A related question is: @kotarohara, when a user marks a segment as unauditable/unwalkable, do we store that in the database so that we can differentiate it on analysis?

-----

Also, the first option shouldn't decrease the progress either. There were two instances in the video when that happened: at [7s](https://youtu.be/60rdcNztxGc?t=7s) and [37s](https://youtu.be/60rdcNztxGc?t=37s)

**Comment by kotarohara** [comment] 2016-09-07 19:53
Selecting the first option updates (decreases) the mission completion rate if you are in a middle of the street edge. You are basically canceling what you have done in that task, so this is an expected behavior. Label data and interaction log will be stored, but task will be marked as incomplete. 

Selecting the second option ("I cannot go...") **should** increase the mission completion rate. The street segment that is skipped with the second option is stored in `sidewalk.street_edge_issue` table.

**Comment by jonfroehlich** [comment] 2016-09-07 20:38
So, what should we do about this? @manaswis? @kotarohara?

@kotarohara did answer an important question related to:

> A related question is: @kotarohara, when a user marks a segment as unauditable/unwalkable, do we store that in the database so that we can differentiate it on analysis?

He said:
> Selecting the second option ("I cannot go...") should increase the mission completion rate. The street segment that is skipped with the second option is stored in sidewalk.street_edge_issue table.

**Comment by jonfroehlich** [comment] 2016-09-08 00:56
@manaswis, are you satisfied with @kotarohara's answer. Do you think we should be doing something differently? Does his answer correspond with your actual experience or are their disparities?

**Comment by manaswis** [comment] 2016-09-08 15:05
Okay, there are a couple of questions to better understand the underlying process:

> Jon: What's likely happening is that the current location that you are standing in when you click jump to another area, is being marked as audited

Does that mean the entire street segment is marked as audited from where you jumped? 

> Kotaro: Selecting the first option updates (decreases) the mission completion rate if you are in a middle of the street edge. You are basically canceling what you have done in that task, so this is an expected behavior. Label data and interaction log will be stored, but task will be marked as incomplete.

Are we penalizing the user for not completing the task? But what about the labels he/she has contributed in that task? Are we discounting those contributions made by decreasing the completion rate? 
Also, question about the completion rate updation process, isn't the completion rate changed after the user contributes by walking? If yes, then it is actually reflecting the work he has already done. Why are we decreasing the completion rate?

Note, in the video, I didn't walk at all when I clicked the jump options. I was dropped either at the start (or almost near the start) of a street segment or near an intersection. So I believe I wasn't in the middle of a street segment. (For reference, here's the video: [https://youtu.be/60rdcNztxGc](https://youtu.be/60rdcNztxGc) - notice the jumps and the avataar's position on the street)

Please correct me if I am wrong in my understanding anywhere.

**Comment by kotarohara** [comment] 2016-09-08 15:41
> Does that mean the entire street segment is marked as audited from where you jumped?

Yes

> Are we penalizing the user for not completing the task? But what about the labels he/she has contributed in that task? Are we discounting those contributions made by decreasing the completion rate? 

No. We are just marking the task as `incomplete` when the user simply skips (by selecting the first option). The user will be routed to the same street segment later. 

> Also, question about the completion rate updation process, isn't the completion rate changed after the user contributes by walking? If yes, then it is actually reflecting the work he has already done. Why are we decreasing the completion rate?

Can you clarify a little bit? I didn't really get this part.

> Note, in the video, I didn't walk at all when I clicked the jump options. I was dropped either at the start (or almost near the start) of a street segment or near an intersection. So I believe I wasn't in the middle of a street segment. (For reference, here's the video: https://youtu.be/60rdcNztxGc - notice the jumps and the avataar's position on the street)

That's probably because you "walked" a little bit. Note, when a user jumps to another location by skipping, (i) we randomly select the next street segment in the current neighborhood, (ii) we query the latlng coordinate where GSV is available based on the latlng coordinate of the selected street segment, and then (iii) drop the user to the latlng coordinate returned by the Street View API. There could be a slight gap between the two coordinates (GSV coordinate and the latlng coordinate used to query the GSV coordinate), so we could end up dropping them slightly off from the coordinate we used to query. As a result, the user could get dropped slightly into the street. Consequently, they could get a few % of progress.

**Comment by manaswis** [comment] 2016-09-08 15:50
>Also, question about the completion rate updation process, isn't the completion rate changed after the user contributes by walking? If yes, then it is actually reflecting the work he has already done. Why are we decreasing the completion rate?

To clarify, what I meant was when you start walking the mission completion rate is updated. So it is getting updated based on how much you moved. So why is it decreasing even if the user is in the middle of the street segment and jumps at that point?

**Comment by manaswis** [comment] 2016-09-08 15:54
Thanks for the other responses. Few other questions:

>Does that mean the entire street segment is marked as audited from where you jumped?
>Yes

>Are we penalizing the user for not completing the task? But what about the labels he/she has contributed in that task? Are we discounting those contributions made by decreasing the completion rate?
>No. We are just marking the task as incomplete when the user simply skips by selecting the first option. The user will be routed to the same street segment later.

Aren't both the answers contradicting? If the street from where you jumped is marked as `audited` then when is it marked as `incomplete`?

Am I missing something here?

**Comment by kotarohara** [comment] 2016-09-08 16:02
No, please read the previous posts. 

If the user selects the first option, which simply skips the task, then the task is marked incomplete. In this case the user does not get a credit.

If the user selects the second option that indicates GSV is not available and thus cannot advance with the task, then the street segment is marked as audited. In this case the task is marked as `competed`.

**Comment by manaswis** [comment] 2016-09-08 16:06
Okay. Then there has been some miscommunication. The previous comment:

> Jon: When choosing the first option, I agree that the progress bar probably should not increase. What's likely happening is that the current location that you are standing in when you click jump to another area, is being marked as audited
>
>Does that mean the entire street segment is marked as audited from where you jumped?
>Yes

The question was referring to the first option in the post.

Anyway, thanks. This clears it up.

**Comment by kotarohara** [comment] 2016-09-08 17:12
Great! I'm closing it, then.

**Comment by manaswis** [comment] 2016-09-08 17:15
Wait, you didn't answer the following comment:

>Manaswi: Also, question about the completion rate updation process, isn't the completion rate changed after the user contributes by walking? If yes, then it is actually reflecting the work he has already done. Why are we decreasing the completion rate?
>
>Kotaro: Can you clarify a little bit? I didn't really get this part.
>
>Manaswi: To clarify, what I meant was when you start walking the mission completion rate is updated. So it is getting updated based on how much you moved. **So why is it decreasing even if the user is in the middle of the street segment and jumps at that point?**

**Comment by kotarohara** [comment] 2016-09-08 17:23
The task is marked as `incomplete` and the user does not get credit for auditing that street. So the progress rolls back.

**Comment by kotarohara** [comment] 2016-09-12 20:29
@manaswis Can I close this?

**Comment by manaswis** [comment] 2016-09-12 20:30
Sure.

**Comment by manaswis** [comment] 2016-09-12 20:31
If I have a better idea of doing this later, then I will reopen it :)

**Closed** 2016-09-12 20:36 UTC
Labels: bug, discussion
