### ISSUE TITLE
First Goal in New Neighborhood Should Reset to Smallest Distance

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#184] opened 2016-07-09 15:35 UTC
I believe that missions were meant to be neighborhood specific; however, after I finished my first full neighborhood (Mt. Vernon Square), I was assigned Logan Circle and my first mission was to make 4miles of that neighborhood accessible. Shouldn't 4 miles be far less--like the initial mission distance of 1,000ft (or whatever it is)? I'm confused.

![image](https://cloud.githubusercontent.com/assets/1621749/16708642/24710410-45c9-11e6-97fb-c3ee1cc2124c.png)

**Comment by kotarohara** [comment] 2016-08-02 20:10
It actually should reset the missions. I will look into it.

**Comment by jonfroehlich** [comment] 2016-08-02 20:12
OK. Good, I agree that this should be the intended behavior. Missions should be neighborhood specific so when you start a new neighborhood, you should begin with the initial mission and progress from there.

**Comment by kotarohara** [comment] 2016-08-11 13:56
Wrote a bunch of tests but I cannot reproduce the bug, so I'm guessing I've fixed it while I've been fixing other parts. I'm closing this issue.

**Closed by kotarohara** 2016-08-11 13:56 UTC
Labels: bug
