### ISSUE TITLE
Walking straight arrow on the GSV screen disappears

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#274] opened 2016-08-31 04:57 UTC
See this video:
https://youtu.be/yIlgpleulLs

On one of the missions, the walking straight arrow disappears and I am unable to move ahead to complete my mission.

**Comment by kotarohara** [comment] 2016-08-31 07:37
This is because of the underlying Google Maps API. The next Street View is not connected by a link. Could you double click and move forward?

**Comment by jonfroehlich** [comment] 2016-08-31 10:30
I think the double click on the road to move forward is a very subtle interaction and something we likely need to tell the users more about. I would be curious to see how often users actually use this...

- While we onboard it in the tutorial, even here, it's very subtle because you only do it once and you don't take much of a step, so it's hard to even recognize that it happens.
- Moreover, in comparison to the direct click on the movement arrows, it is a less visible interaction.
- I find myself clicking the movement arrows more because sometimes the double clicks on the roadway don't work (maybe 10% of the time)--it happens enough that this unreliability causes me to just use the arrows. I do still double click the roadway though to move, just less often than I probably would if it *always* worked

Also, and most relevant to @manaswis's post, it would be great if we could somehow add a pop-up or something that tells the user at this point to double click on the roadway to move forward.

**Comment by kotarohara** [comment] 2016-09-01 04:41
So this is not a bug. I propose to close this issue and create a feature request as a "Future Work"

**Comment by jonfroehlich** [comment] 2016-09-01 10:24
I don't think we should close the issue. I think we should discuss it as a team, provide perspectives on whether we think it's important enough to address, and, if it is, how to address the issue (e.g., should we simply add an animated gif to the FAQ that better shows that you can double click on road to move forward or should we improve onboarding or is there anyway to determine that the walking arrow disappears and, at that point, to provide a contextually relevant pop-up that tells them what to do).

**Comment by manaswis** [comment] 2016-12-07 20:03
Submitted the PR (#468) for this issue. Screenshot of the entry below:

<img width="857" alt="screen shot 2016-12-07 at 3 00 06 pm" src="https://cloud.githubusercontent.com/assets/2873216/20984451/4be067ca-bc8e-11e6-88d6-d18f6eb76828.png">

**Closed** 2016-12-08 16:30 UTC
Labels: bug, For FAQ, pull-request-submitted
