### ISSUE TITLE
Very Rare Bug: Asked to Jump And Sign-in At Same Time...

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1072] opened 2017-09-07 18:20 UTC
So, I was just auditing as an anon user to test the production system and make sure things are working.

I got to the end of an audit route where the bottom-right corner says "OK, you're done with this area, click here to jump to another area" but before I could click on that, I got the pop-up dialog that says "You've been auditing alot... why don't you register..." and then when I clicked "No, I don't want to register" the bottom-right corner no longer said "OK, you're done with this area..." so I was stuck.

However, I figured that if I took a step, I would get the "Uh oh, you are quite far off the route..." message and that's just what happened. So, once I clicked that, things were fixed/fine.

Very low priority but I figured we should log this bug. Sorry no screenshots. Hope my explanation was clear.

Update: and the mission complete progress bar no longer works. Not sure if this is related. Console shows no errors.

![image](https://user-images.githubusercontent.com/1621749/30178878-66366fe4-93bf-11e7-8ef4-dfbe758b20ab.png)

Update 2: Now seems to be updating progress bar--I'm on the same mission.

![image](https://user-images.githubusercontent.com/1621749/30179083-0146f4f4-93c0-11e7-833d-98359097b5dc.png)

**Comment by manaswis** [comment] 2017-09-07 20:21
Yep this error is logged in https://github.com/ProjectSidewalk/SidewalkWebpage/issues/702

**Comment by misaugstad** [comment] 2017-09-17 00:32
Closing since this is a duplicate of #702

**Closed by misaugstad** 2017-09-17 00:32 UTC
Labels: bug
