### ISSUE TITLE
Admin Interface: Placement of label in the label view panorama seems to be incorrect

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1147] opened 2017-10-16 20:30 UTC
This might be due to
 - Incorrect placement of labels by the user
 - Incorrect calculation of the position of the label in the panorama by the visualization code.
Needs investigation
![](https://files.slack.com/files-pri/T5G48AFJN-F7K5H26LV/image.png)

**Comment by maddalihanumateja** [comment] 2017-10-16 20:30
![image](https://user-images.githubusercontent.com/3580069/31633727-4d3f25b4-b28f-11e7-83f8-2cbbf7ebed25.png)

**Comment by misaugstad** [comment] 2017-12-01 17:45
This definitely seems to be that calculation of the position of the label on the panorama is off. @manaswis what do you think might be the cause? And do you think it is something that an undergrad could fix without too much trouble?

**Comment by misaugstad** [comment] 2018-10-03 23:52
Closing via #1308

**Closed by misaugstad** 2018-10-03 23:52 UTC
Labels: NextCity, Priority: Low, bug, pull-request-submitted
