### ISSUE TITLE
Google street view error does not always work as intended

### ISSUE THREAD

**Issue by sagec108** [ProjectSidewalk/SidewalkWebpage#608] opened 2017-05-24 20:47 UTC
I have noticed that recently, the Google Street View error pops up a lot. I believe this error pop-up is not working as intended and tested by stopping at an instance when the error was shown and retrieving location information. I compared said information in Google Maps, where I found no issue with street view images at the exact same longitude and latitude.

One example I found while at the exact same coordinates:

Info: 
Location: Georgetown Reservoir, DC
Pano ID: "8CcH2fexirhdpqtONc-hPw"
Coordinates: Object { lat: 38.90964603739818, lng: -77.0810721205952 }
Street ID: 1987

Sidewalk Webpage:
![image](https://cloud.githubusercontent.com/assets/20068009/26424814/833caa08-40a0-11e7-9ca0-6544bd85e7dd.png)

Google Maps:
![image](https://cloud.githubusercontent.com/assets/20068009/26424732/391e8450-40a0-11e7-94c8-d4c54a6ef746.png)

I will investigate more to see what kind of errors are being thrown in the Google API.

**Comment by jonfroehlich** [comment] 2017-05-24 20:53
Thanks Sage. 

This is a high priority and needs to be  investigated and fixed ASAP, especially if it's now high occurrence. 

How prominent is the issue?

Others: this is the reason that you should regularly complete missions with our tool.

**Comment by manaswis** [comment] 2017-05-24 20:57
As I mentioned it to Sage, this could be caused due to the recent API update. It is possible that they changed how they handle errors. 

@sagec108 I would start by looking into the specific error that is being thrown by the API in these cases.

**Comment by sagec108** [comment] 2017-05-25 17:52
So, while the GSV error is displayed somewhat frequently, I'm not sure if there's a fix.
I investigated and found that the error is displayed when the Google API's pano_changed event occurs and the panorama ID is undefined. The strange thing is that the following pano_changed events have defined panorama IDs consistent with those from before. To make this issue clearer, I logged variables into the console:

![image](https://cloud.githubusercontent.com/assets/20068009/26459790/aceb403a-4145-11e7-80c2-ef065f8859f3.png)

A solution I found was to make the function that handles panorama changes immediately return back to the calling code if given an undefined panorama ID. After testing, I was able to complete 4 missions without a single GSV error popping up.

However, what requires discussion is whether we can/should ignore the occasional undefined panorama ID, especially if we reach an area where GSV is _actually_ incomplete.

**Comment by misaugstad** [comment] 2017-05-26 00:17
In your image, it is not clear at what point the pano_changed event occurs. Also what is the difference between "Googel API Panorama" and "Pano ID"?

As for ignoring the undefined panoramas: we definitely can't outright do that; as you said, when there actually _isn't_ a panorama, we need to have that error message pop up and move them to a new location. The easy way out could be to implement a sort of "timing out", where maybe we do what you suggested, but if a full second passes (or whatever it may be), then we let the error message pop up. I don't really like that as it is really hacky and doesn't get at the root of the problem. We really do need to find out what the root of the problem is.

**Comment by sagec108** [comment] 2017-05-26 14:41
The "Google API Panorama" line being printed is for calling the function getPanorama, making sure for each Pano ID received the code successfully queries panorama information from the Google API. 

The pano_changed event itself occurs before each "Pano ID: ..." print. So, the order goes 
1. Event 
2. getPano() which gets the Pano ID, where I print only the ID
3. getPanorama(....), where I print ID and status

**Comment by jonfroehlich** [comment] 2017-05-26 19:33
Who is currently working on this problem? It seems like it should be elevated to @manaswis if it is, indeed, a far more common occurrence than it was. Please update the status.

I'm fine with @sagec108 continuing to lead this with oversight from @manaswis; however, I want to see more information on the problem: how often is it occurring? Is it reproducible? Do we have any ideas for how to solve it?

**Comment by sagec108** [comment] 2017-05-26 19:45
For now, I am the one currently working on this problem. I do not have a hard measure of how often it is occurring, though from my experience I can easily get at least 1 of these GSV errors in every 2 missions I try. 

For ideas to solve it, I mentioned above that by ignoring the undefined pano ID given by Google's API, the missions will work smoothly. This does not affect when there actually is no panorama, as I think that is handled by ensuring that google returns an "OK" status.

@manaswis suggested that I use an older idea of reacting to an undefined pano ID by moving forward another step and checking the pano ID again. If the user reaches a streak of undefined IDs (e.g. 3), then the error message can pop up.

**Comment by jonfroehlich** [comment] 2017-05-26 20:50
If it is truly occurring on 50% of the missions, then this is a very high priority problem. 

Re: older idea. Yes, the idea here was to _silently_ move the user forward along the direction they clicked and check the pano ID at that location. If you the code encounters a streak of undefined IDs, we pop-up the message. Note, however, that @manaswis tried to do this and never solved the problem. Perhaps she's confident that a fresh set of eyes will do better, which can be the case.

I remain concerned when a core part of Sidewalk breaks like this. I'd really like to see the team rally around solving the problem efficiently and effectively (thanks @misaugstad for https://github.com/ProjectSidewalk/SidewalkWebpage/issues/608#issuecomment-304158025).

**Comment by manaswis** [comment] 2017-05-29 19:52
I did some testing of my own. So the first step is to remove the code that shows that message when the pano id is not defined. 
@sagec108 remove the else part of `(svl.streetViewService && panoId.length > 0)`  condition and retain the condition that you added `(typeof panoId === "undefined")`. I modified it to be `(typeof panoId === "undefined" || panoId.length == 0)`. Also, within that block add the compass code block. This will solve the part of the problem of pop-up showing up frequently. I checked if this works in places where there isn’t any GSV available, and it does.

Second part is about the speed problem when the pano id is not set properly. It doesn’t create a problem now. However, it might. Here is what the API doc says about `pano_change`: 

> “pano_changed fires whenever the individual pano ID changes. **This event does not guarantee that any associated data within the panorama (such as the links) has also changed by the time this event is triggered**; this event only indicates that a pano ID has changed. Note that the pano ID (which you can use to reference this panorama) is only stable within the current browser session.”

So if the metadata is not set properly, then it might have some unknown consequences. The solution that we discussed today is possibly restricting too fast (>2 key presses per sec) movements. Google Street View does that on their main website as well. It doesn’t allow you to move 2 steps even if you pressed the forward arrow key twice. Moving forward only happens after you reach the next position from your initial forward key press. So we could also think about doing something like this.

**Comment by manaswis** [comment] 2017-05-29 20:00
After you modify the code to not show the popup, this is what happens when move too fast (when the pano id is undefined):

![image](https://cloud.githubusercontent.com/assets/2873216/26560811/5880b684-4487-11e7-8ece-ea177ba5b830.png)

This warning is also shown on the console (haven't seen this before):
`.Offscreen-For-WebGL-0x7f960db07e00]RENDER WARNING: there is no texture bound to the unit 0`
![image](https://cloud.githubusercontent.com/assets/2873216/26560826/6db09650-4487-11e7-9e54-18d272ac0ad0.png)

**Note**: The black screen goes away by just moving forward/backward because the pano ids do exist at these locations. 

So we should implement a solution for the speed problem -- restricting movement is one such solution (as mentioned in the previous comment) as done by Google Street View as well.

**Comment by manaswis** [comment] 2017-05-29 20:09
To add, this is the calling flow when we press forward in quick succession:

![image](https://cloud.githubusercontent.com/assets/2873216/26560929/1c59f124-4488-11e7-8dbc-55f28ba40f12.png)

Pano Ids:
`YEZ8nXjSLbbBaL3i7cLFuw` is the pano id for the first step
`T1nT7bhUc3o2pNUl81ehpQ` is the pano id for the second step taken

To note:
1. "I am called" is the text that's printed when the forward key is pressed.
2. Each time you take a step, the pano_change event occurs twice. Which is why you see 2 block fo statements for each pano change.

PanoID and Google API statements are the result of the pano ids being printed in two different locations in the code. That's not the important part to note here.

**Comment by misaugstad** [comment] 2017-05-30 01:08
I think it makes sense to complete a step forward before allowing another step to start. I also really think that it is notable that this is how google.com/maps works. I would think that enforcing synchronization could eliminate some really hard to debug errors that could come up over the life of a project. Maybe this is one of those times where it would be useful. (both to prevent errors stemming from concurrent requests and to make it harder for users to just click through a route.

**Comment by jonfroehlich** [comment] 2017-05-30 01:20
Thanks for investigating this further @manaswis. I agree with you both (@manaswis and @misaugstad) that we can follow the same paradigm as the actual GSV and prevent a step forward before the current step has completed.

I want to make sure I understand the problem, however, which seems to be twofold:
1. Sometimes there is no panoid at a location. This is the problem that @manaswis was previously trying to solve this past semester. Do we have a solution for this other than just popping up the error message? Does it make sense to still pursue the solution of trying to re-request the pano at the current location (1-3 times) and if null, then move 1 step in the direction the user was moving and repeat (repeat maybe ~2 times before then putting up the error message).

2. The user can cause a panoid load error by moving too quickly. We can resolve this by prevent user from taking a step before current location finishes loading.

**Comment by manaswis** [comment] 2017-05-30 14:22
@jonfroehlich 

> Sometimes there is no panoid at a location. This is the problem that @manaswis was previously trying to solve this past semester. Do we have a solution for this other than just popping up the error message? Does it make sense to still pursue the solution of trying to re-request the pano at the current location (1-3 times) and if null, then move 1 step in the direction the user was moving and repeat (repeat maybe ~2 times before then putting up the error message).

The issue was that the pano id had no imagery or the location where the user wanted to move by double clicking didn't have imagery. We solved this by showing the pop-up message that moved the user to another location on clicking the OK button. We could try again to look into the solution of walking 2 - 3 steps. The new API version might have resolved the issue that I originally faced. It was around multi-threading and pano-id not being set in each step.

> The user can cause a panoid load error by moving too quickly. We can resolve this by prevent user from taking a step before current location finishes loading.

Yes, we should do this. I have asked @sagec108 to resolve the current issue by the small change I mentioned earlier that doesn't show the pop-up when the pano id is undefined and create a new issue for handling the speed problem and tackle it there.

**Comment by jonfroehlich** [comment] 2017-05-30 20:32
Thanks @manaswis. Do we know how often #1 happens (with new API)?

**Comment by manaswis** [comment] 2017-05-30 20:48
To clarify: The new API version might make it easier to implement our solution of taking 2 - 3 steps where there isn't GSV available. So the issue in point 1 won't be affected by the new API, only the solution of taking step would. I updated the previous comment to reflect this.

**Closed** 2017-06-21 01:16 UTC
Labels: Priority: High, pull-request-submitted
