### ISSUE TITLE
Include userid in attributesWithLabels API call

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2969] opened 2022-07-20 19:27 UTC
It does not appear that our `attributesWithLabels` API call includes the userid for each labelid (it should).

For example:
https://sidewalk-validation-study.cs.washington.edu/v2/access/attributesWithLabels?lat1=41.56&lng1=-87.885&lat2=41.59&lng2=-87.847&severity=3

Returns

```
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[-87.88111114501953,41.58243179321289]},"label_geometry":{"type":"Point","coordinates":[-87.88111114501953,41.58243179321289]},"properties":{"attribute_id":8394,"label_type":"CurbRamp","street_edge_id":470,"osm_street_id":722465987,"neighborhood":"Orland Park","severity":3,"is_temporary":false,"label_id":758,"gsv_panorama_id":"x7NAAIfCL5VnQJ87X3Zyqw","heading":111.71553802490234,"pitch":-12.560267448425293,"zoom":3,"canvas_x":381,"canvas_y":134,"canvas_width":720,"canvas_height":480,"gsv_url":"https://maps.googleapis.com/maps/api/streetview?size=720x480&pano=x7NAAIfCL5VnQJ87X3Zyqw&heading=111.71554&pitch=-12.560267&fov=27.68198649088542&key=YOUR_API_KEY&signature=YOUR_SIGNATURE","label_severity":3,"label_is_temporary":false,"agree_count":1,"disagree_count":0,"notsure_count":0}}]}
```

I don't see userid here. Or am I wrong @misaugstad and @zoekaputa?

**Comment by misaugstad** [comment] 2022-07-20 19:29
Duplicate of #2889

**Closed by misaugstad** 2022-07-20 19:29 UTC
Labels: Duplicate, API
