### ISSUE TITLE
Ajax Synchronous Request Failing on page unload events in Chrome

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1648] opened 2019-04-17 12:27 UTC
As @aileenzeng originally identified here, she came across the following [bug](https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1645#issuecomment-483932975):

> "NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://0.0.0.0:9000/task': Synchronous XHR in page dismissal."
> 
> From this [StackOverflow post](https://stackoverflow.com/questions/55676319/ajax-synchronous-request-failing-in-chrome), it looks like it's because chrome doesn't allow synchronous ajax requests anymore. Apparently using [a beacon](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API/Using_the_Beacon_API) is the alternative others are using, but it looks like it's still an experimental feature.

We need to review all places that we use a synchronous AJAX call and begin coming up with alternatives.

**Comment by aileenzeng** [comment] 2019-04-17 13:53
Copied from #1645:

> Hold on - I think the second concern that’s I brought up (RE: sendBeacon not returning values) might not actually be a problem. I think we are actually allowed to use synchronous AJAX calls in our code (like when we do finish a mission) - just as long as it’s not called before unloading the page.

**Comment by misaugstad** [comment] 2019-04-23 21:35
@tongning could you actually take up this smaller and more pressing issue before you get back to resizing the GSV window? See if you can find an alternative to the synchronous ajax requests on page unload that works on all browsers? :grin:

**Comment by jonfroehlich** [comment] 2019-04-23 23:52
Yes!

**Comment by tongning** [comment] 2019-04-24 18:55
Got it, I'll look at this before GSV resize 👍

**Comment by misaugstad** [comment] 2019-05-06 17:27
@tongning do you think you'll have time to work on this this week?

**Comment by tongning** [comment] 2019-05-06 19:24
Unfortunately I've been flooded since last week (final projects in almost all of my classes, ugh) and I don't see this lightening up soon with finals coming up. I think I'll be able to work on this in earnest starting end of next week, but if that is too long of a delay then feel free to reassign the issue. Sorry for the delay 🙁

**Comment by misaugstad** [comment] 2019-05-06 20:49
No problem @tongning school happens :)

@andrew4699 do you have time this week to take a look at this issue? As something higher priority than the unified login.

**Comment by andrew4699** [comment] 2019-05-06 22:05
I can take a look today, but I do have 2 midterms this week that I'll have to start preparing for soon so from tomorrow to Friday I'll be dodgy.

**Comment by andrew4699** [comment] 2019-05-13 21:24
Can someone try out this branch and see if the issue still occurs? **1648-logging-unload-logging-failing**

I created a custom route (/postBeacon) for the beacon and I'm transforming the data from the beacon format (JSON plaintext) to actual JSON and sending it to our normal route (/post).

I'm testing this by seeing if the "Unload" event gets logged properly, and it does on Chrome & Firefox. @misaugstad perhaps there's other things that should be tested too?

**Comment by misaugstad** [comment] 2019-05-13 21:40
@andrew4699 although it is a bit redundant, I would test that things like labels are being recorded when placed right before a page refresh.

Going to be traveling (to Seattle!) tomorrow, so I probably won't be able to test until at least Wednesday. Anyone else want to jump in and test as well (while making sure you can reproduce the bug on develop first)? @aileenzeng @htadeusiak @tongning

**Comment by andrew4699** [comment] 2019-05-13 21:58
Just a note about reproducing on develop, you'll want to comment out @misaugstad 's temporary fix in "public/..../SVLabel/..../Form.js" since that's what we're trying to replace. The line to comment out is the **self.submitData** line after the "TODO: Replace with beacon (or some ajax alternative) asap. Starter code below" comment

**Comment by andrew4699** [comment] 2019-05-13 22:04
Also I just tested label creation and the label does in fact get logged when you unload.

**Comment by misaugstad** [comment] 2019-05-15 18:29
Tested and it is working for me!

**Comment by misaugstad** [comment] 2019-05-30 20:26
closing via #1740

**Closed by misaugstad** 2019-05-30 20:26 UTC
Labels: Priority: Very High, in progress
