### ISSUE TITLE
Can't Move in the Middle of a Mission

### ISSUE THREAD

**Issue by danZzyy** [ProjectSidewalk/SidewalkWebpage#200] opened 2016-07-29 16:27 UTC
This is something new I encountered on my local server. I am not sure I have seen this happen before.  I am placed in a mission, take one step, and cannot move because I get this error :
![image](https://cloud.githubusercontent.com/assets/13355765/17255556/c07aedda-5587-11e6-97f4-4e1a8105ceb3.png)

**Comment by kotarohara** [comment] 2016-08-02 19:44
I will look into it. From next time, please provide more informative bug report! A report with a failing test case will be helpful too.

**Comment by kotarohara** [comment] 2016-08-23 15:34
Can't reproduce. I'm closing this.

**Closed by kotarohara** 2016-08-23 15:34 UTC
Labels: bug
