### ISSUE TITLE
Can't signup on new Columbus server

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1963] opened 2019-11-13 13:26 UTC
I didn't think my account/credentials for jonfroehlich transferred over to Columbus, so I tried signing up this morning but failed. Unfortunately, it's one of those frustrating *silent* fails. See video:

https://youtu.be/UWScjQxNTQ0

**Comment by jonfroehlich** [comment] 2019-11-13 13:34
Here's another user flow for signing up but it didn't work either: https://youtu.be/CO815--iA1U

(Note that I accidentally closed the sign up pop-up but got it back--you'll see).

**Comment by misaugstad** [comment] 2019-11-16 03:52
@jonfroehlich couldn't sign in bc he was using the wrong email address. in the videos are issues where he couldn't sign up which are big problems that should be addressed.

**Comment by jonfroehlich** [comment] 2019-11-18 18:42
Right, but the video does highlight multiple problems with our signup user flow, as you said. These are important to fix.

**Comment by misaugstad** [comment] 2019-11-18 22:25
Ok the problem is that we don't have an error message show up when you provide a password that is less than 6 characters on that /signUp page. We do have it for the modal that shows up if you click the sign in button on the navbar, but not on the dedicated page.

![pw-6-characters](https://user-images.githubusercontent.com/6518824/69099227-1b7a2b80-0a0f-11ea-8589-1f79b38ff4f1.png)
 
I'll make sure those checks are added to this page :)

**Comment by misaugstad** [comment] 2019-11-20 20:24
Oops it is actually worse than this. When we started requiring typing your password twice when signing up, we didn't include that on both pages. so signing up just does not work at all on this page, oops! The original PR is #1755 

I'll move all that functionality over.

**Comment by misaugstad** [comment] 2019-11-20 21:14
closing via #1972

**Closed by misaugstad** 2019-11-20 21:14 UTC
Labels: Priority: Very High, bug
