### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3251] opened 2023-06-01 13:42 UTC
Our collaborators in Zurich just created German translations for us.

[projectsidewalkzurichtranslatedfiles.zip](https://github.com/ProjectSidewalk/SidewalkWebpage/files/11625955/projectsidewalkzurichtranslatedfiles.zip)

**Comment by misaugstad** [comment] 2023-06-01 17:20
Closing as duplicate

**Comment by misaugstad** [comment] 2023-06-01 17:21
Duplicate of #3219 that is!

**Closed by misaugstad** 2023-06-01 17:20 UTC
Labels: Internationalization
