### ISSUE TITLE
Intersection done dialog pops up before it is completed

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#269] opened 2016-08-30 03:49 UTC
Lee: In the first real mission I did (River Terrace, D.C.), a message popped up telling me that I was done and should move on, but I had only actually finished 3/4 corners.

**Comment by jonfroehlich** [comment] 2016-08-30 11:00
So, to be clear, Lee was speaking about the tutorial pop-up that only comes up in the first mission and does so telling the user to start walking after they clear the first intersection. However, there is no real way to know if they clear the intersection, so we only track *where* they look and then the pop-up comes up when they've looked like 300 degrees around or something. @kotarohara can provide more details.

@manaswis, to investigate this more, you should complete the tutorial a few times as an anonymous user and see if it happens to you. Again, it happens after you complete the tutorial but early on in your first mission.

**Comment by kotarohara** [comment] 2016-08-30 15:19
I guess Lee is talking about this window. It shows up once you looked around 7/8 of the intersection. So it's not a bug. @manaswis you can close it.

![cursor_and_project_sidewalk_-_audit](https://cloud.githubusercontent.com/assets/612263/18094929/4052f97e-6ea3-11e6-8c62-d267ac5d385c.png)

**Comment by jonfroehlich** [comment] 2016-08-30 16:22
I don't think it should be closed because it confused a user, which means we should at the very least discuss the problem and whether it justifies redesign/improvement. Lee is a very smart, technical guy. If this confused him, what will others think?

**Comment by kotarohara** [comment] 2016-09-01 04:42
I don't know what to do with this issue. @manaswis @Soben713 any comments?

**Comment by jonfroehlich** [comment] 2016-09-01 10:21
I have two suggestions:

1) We could do some over-the-shoulder observations of people completing the tutorial plus this part of the first mission and see what they think when this pop-up occurs. My feeling is that if we tell someone they have finished auditing an intersections when they really haven't, then this is confusing. There are lots of new students around the lab right now with the start of the semester, so I'm guessing we could grab 2-3. Ideally, we would find some older, less-technical users as well...

2) We could make the threshold different (e.g., rather than 7/8, which is 87.5%, have something like 95% or even 100%)

**Comment by Soben713** [comment] 2016-11-07 22:45
After looking at the code, I found two bugs in the code which may have caused the confusion.

1. Currently, in certain cases,  the pop-up may appear even when the user has viewed less than 1/4 of the intersection. Here is a video of that: https://www.youtube.com/watch?v=pOHmRuIicMk&feature=youtu.be
2. I believe this message should not appear if the user has already started walking. But it is not currently taken into account. For example, if a user only views 50% of the first intersection then moves forward and views 38.7% of another scene after walking, then they get this message that "you finished auditing the _intersection_", while they might not even be at an intersection.

Here is what I'll do to resolve this issue:

- Fix the bugs.
- Change the message to something clearer and less magical. My suggestion: _"We detected that you viewed the whole scene. If you finished auditing this place, follow the red line in the map to complete your mission. We provide turn-by-turn instructions to guide your path."_

**Comment by jonfroehlich** [comment] 2016-11-08 01:26
Nice @Soben713. I agree with everything you said.

I think the message needs a bit of work. My take: "_It looks like you've looked around this entire intersection. If you're done labeling this place, it's time to take a step. Walk in the direction of the red line highlighted on the map. We provide turn-by-turn directions to guide your path._" Probably too long. :(

PS Could you copy/paste in the current message?

**Comment by Soben713** [comment] 2016-11-08 01:30
@jonfroehlich I agree that the message is too long. Maybe we can remove the second part where it says "We provide turn-by-turn directions to guide your path"?

This is the current message:

> Great! It looks like you finished auditing this intersection. Now, follow the red line in the map to complete your mission. We provide turn-by-turn instructions to guide your path.

**Comment by Soben713** [comment] 2016-11-08 03:00
This is how the message looks. Seems too long.

![image](https://cloud.githubusercontent.com/assets/1576529/20085207/3ae18226-a535-11e6-8344-e14ee0c1dd36.png)

Without the last sentence:

![image](https://cloud.githubusercontent.com/assets/1576529/20085260/91d3fb2c-a535-11e6-9b67-f4c2710e7b51.png)

**Comment by Soben713** [comment] 2016-11-08 05:44
This was resolved in PR #398. @jonfroehlich I used your suggestion for the popup message but removed the last sentence. If you have any other suggestion let me know and I'll change it.

**Comment by jonfroehlich** [comment] 2016-11-08 19:51
I think we can improve the message a bit by:

- highlighting the 'turn-by-turn' directions somehow
- highlighting the top-down map

Maybe we use yellow highlights? And then refer to these in the message?

**Comment by Soben713** [comment] 2016-11-08 22:54
@jonfroehlich Oh wait, I just noticed what "turn-by-turn" direction means. Is it that direction box in the street view panel? We currently highlight both the map and that box when this message is shown.

**Comment by jonfroehlich** [comment] 2016-11-11 14:33
@Soben713. Yes, that's what I meant by 'turn-by-turn' directions. If we already do this, then we're good (as long as we think the flashing yellow highlights are salient enough).

**Closed** 2016-11-17 01:40 UTC
Labels: bug, Priority: Low, pull-request-submitted
