### ISSUE TITLE
Admin Interface: How Can Neighborhood Completion % Be Above 100?

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1078] opened 2017-09-11 22:48 UTC
How can neighborhood completion rates go beyond 100? Is this because we allow folks to audit neighborhoods that are already complete? Either way, probably there is a better way to visualize this :-P

![image](https://user-images.githubusercontent.com/1621749/30300241-8185a156-9708-11e7-836c-56b07c545fd1.png)

**Comment by misaugstad** [comment] 2017-09-11 23:00
Because our calculation of distance is different in different places. I submitted a PR ( #884 ) that I thought had fixed this, but @manaswis ran into an occurrence of the completion going over 100% even in that PR, and I haven't been able to reproduce it.

Completion going over 100% is noted in issue #868 
Also, completion may not reach 100% for the same reason ( #870 )

But this only affects visualization, not the underlying logic of the tool, which looks at street segments and sees if there are any remaining that have not yet been audited instead of computing completion percentage of neighborhood...

For the most part. This could become a problem as we get very close to 100% completion, because we do use neighborhood completion to determine which neighborhood to assign to new users. Doesn't matter when there are regions with way less than 100% left though.

Closing this issue, because it describes the same underlying problem as #868

**Closed by misaugstad** 2017-09-11 23:00 UTC
