### ISSUE TITLE
Return to mission vs. Start new mission

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1568] opened 2019-03-18 22:17 UTC
When you finish a single mission in a neighborhood, I think you should get the 'Mission Complete' screen and then a 'Start new mission' screen and not a 'Resume mission' screen. Currently, the latter is happening. I don't believe this was the case previously so I don't know when this change took place. For example, I just finished a mission, received the 'Mission Complete' screen but then received the following 'Resume mission' screen (which shouldn't be happening imo).

![image](https://user-images.githubusercontent.com/1621749/54567363-ca51fd80-4990-11e9-8cd0-769d733ec231.png)

Resuming a mission should be reserved for returning to an incomplete mission. After you finish a mission, you should feel good about that and then feel good about starting a new mission. The word 'resume' makes me feel like I didn't actually finish.

**Comment by misaugstad** [comment] 2019-03-18 22:20
duplicate of #1415

**Closed by misaugstad** 2019-03-18 22:20 UTC
Labels: duplicate
