### ISSUE TITLE
Improve Mission Start screens

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1798] opened 2019-07-12 23:33 UTC
Now that auditing and validation missions are part of one flow, I think it's critical that the Mission Start screens are far easier to read, understand, and immediately grok what type of mission you're doing now.

Folks during hackathon today got confused because the mission screens look really similar...

**Comment by misaugstad** [comment] 2019-07-19 01:17
one idea you've put out @jonfroehlich for improving the validation mission start screen is in #1695

**Comment by misaugstad** [comment] 2021-04-17 20:54
#2152 is a duplicate of this issue, but it includes mocks and more discussion, so I'm closing in favor of that one.

**Closed by misaugstad** 2021-04-17 20:54 UTC
Labels: UI Design, potential-intern-assignment
