### ISSUE TITLE
Idle Window Gets Signed Out Implicitly And Then Missions Completed as Anonymous (Unbeknownst to User)

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#306] opened 2016-09-05 23:05 UTC
It looks like if you leave a tab open and idle with an active audit going for some period of time (not sure how long), you will be implicitly signed out and then if you return to the tab and continue work, you will do so as anonymous (however, the UI will still say your username). 

Also, at least one user has contacted me about this. They started an audit, left the tab open and idle for a while, then returned to it and completed ~1 mile of auditing. However, on the backend, I only see:

![image](https://cloud.githubusercontent.com/assets/1621749/18258016/a1ec8798-739b-11e6-99b8-163b507b6a05.png)

But the user sent me this screenshot verifying their work:
![image](https://cloud.githubusercontent.com/assets/1621749/18258019/b1f8e992-739b-11e6-8daf-e189721e23a2.png)

Perhaps this is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/265?

**Comment by kotarohara** [comment] 2016-09-07 16:34
Yeah, this could be the reason for #265 as I noted in that issue.

**Comment by kotarohara** [comment] 2016-09-07 16:37
I set the authenticated user session to never expire, but it may not be working as I intended.

**Comment by jonfroehlich** [comment] 2016-09-07 16:55
OK, this requires further testing. Maybe @manaswis can start to investigate this on her localhost. Start auditing as a signed in user--then stop and keep tab open and idle for ~1 hour, 5 hours, or whatever--and then return to it and see what happens.

**Comment by manaswis** [comment] 2016-09-07 17:06
Yes, I have seen this too. And this is happening. See the screenshots below. I had signed in at midnight and left the computer (which went to sleep). The user is definitely logged out. And the new labels added using the screen is attributed to anonymous.

<img width="1233" alt="screen shot 2016-09-07 at 1 00 30 pm" src="https://cloud.githubusercontent.com/assets/2873216/18321367/a3e21f3e-74fb-11e6-931b-8917bf378bd3.png">

Admin interface showing the last few labels - added description to differentiate.
<img width="1252" alt="screen shot 2016-09-07 at 1 02 50 pm" src="https://cloud.githubusercontent.com/assets/2873216/18321372/ac749636-74fb-11e6-99c7-1deb2b3084d7.png">

**Comment by manaswis** [comment] 2016-09-07 20:03
I think the timeout is approx. 1 hour.

**Comment by jonfroehlich** [comment] 2016-09-07 20:40
OK, good. Now that we *know* this is happening, we have to investigate *why* this is happening. Is Chrome losing the session? Is the backend session stuff implemented correctly? Etc.

**Comment by kotarohara** [comment] 2016-09-07 20:45
I set the timeout from never to 30 days, so it should address the issue.

**Comment by jonfroehlich** [comment] 2016-09-07 20:46
So you think 30 days timeout will fix it?

**Comment by kotarohara** [comment] 2016-09-07 20:47
I don't say it's a fix as it will timeout after 30 days, but it should address the issue.

**Comment by jonfroehlich** [comment] 2016-09-07 21:35
@manaswis, can you test this too?

**Comment by manaswis** [comment] 2016-09-07 22:16
Sure

**Comment by manaswis** [comment] 2016-09-08 14:16
I tested it. It doesn't seem to work. The user is still timed out. See the screenshot below:

Test 1:
<img width="1260" alt="screen shot 2016-09-08 at 12 06 50 am" src="https://cloud.githubusercontent.com/assets/2873216/18336812/78e45b5a-7558-11e6-85ad-30ace2e173ad.png">

Test 2:
<img width="1262" alt="screen shot 2016-09-08 at 10 13 15 am" src="https://cloud.githubusercontent.com/assets/2873216/18352567/f18070c2-75ac-11e6-9147-f8f554ba77bb.png">

Both times my computer went to sleep. I will try another test where I work on other tabs for an hour and check again.

The side-effect of this bug is that the user might end up auditing same streets again. E.g. when I logged in, I started from the last recorded progress status while I might have already audited them (even though there is some randomness in getting the street segments).

**Comment by kotarohara** [comment] 2016-09-08 15:45
@manaswis Just to make sure, you used the branch that has been updated?

**Comment by manaswis** [comment] 2016-09-08 15:46
Also, there is another concern: Suppose the user leaves the screen at an intersection after labeling it but he/she doesn't move ahead onto any other street segment. If I am not wrong, to record those labels into the database, few interactions (e.g. few steps) are required right? So the user might lose those as well if he doesn't move and then gets timed out. 

Although this is _another issue_. I have noticed this when I add a label, then check the admin interface to see if its reflected there. My latest label most times isn't visible. I just did a thorough testing. It takes between 4 - 10 steps for the labels to be recorded. 

Let me know if it makes sense. If yes, then I will create another issue.

**Comment by manaswis** [comment] 2016-09-08 15:48
@kotarohara Yes, I used the branch that has been updated. I am currently running another test. In both the previous tests, my computer went to sleep so that might have been the cause.

In my current test, I checked I am still logged in after an hour of inactivity. I will continue to test it for a couple of more hours.

**Comment by kotarohara** [comment] 2016-09-08 15:56
> Although this is another issue. I have noticed this when I add a label, then check the admin interface to see if its reflected there. My latest label most times isn't visible. I just did a thorough testing. It takes between 4 - 10 steps for the labels to be recorded.

Ok, can you check if the browser `unload` event is triggered on tab close or page transition? If yes, the data should be stored. If not, that's a problem so please open another issue. Could it be because admin interface only visualizes the labels that are associated to the `completed` tasks? I can't remember the condition for visualizing the labels.

**Comment by kotarohara** [comment] 2016-09-08 15:56
Also, how are you testing timeout?

**Comment by manaswis** [comment] 2016-09-08 16:02
> Also, how are you testing timeout?

I note the time when I left the screen (kept the tab open). I don't interact with the admin interface as well in the same browser coz its using the same session. Then I check after an hour if the admin interface is still logged in. It its not logged in, then the session has timed out. Then, if I use the other tab with the GSV screen, the labels added then are marked by the anonymous user.

**Comment by manaswis** [comment] 2016-09-08 17:11
Result of the third test (where my system didn't go to sleep):

<img width="1258" alt="screen shot 2016-09-08 at 1 05 27 pm" src="https://cloud.githubusercontent.com/assets/2873216/18358824/157265f4-75c5-11e6-8057-0c1a83808bb6.png">

The user identity is maintained on the screen. After returning to the screen, the new labels are added as the signed in user. As long as you are on the screen, your identity is maintained. But if I go to another part of the website, e.g. the dashboard, the user seems to be signed out.

Caveat: I had to update my repo in between for some reason. Not sure, if that has any affect since the GSV screen page didn't reload, so technically there shouldn't be any affect. But the signed out behavior mentioned above might have an effect.

So I will run another test later today when there won't any interruptions, i.e. keeping the tab open, not letting my system sleep and not changing the state of the repo.

**Comment by kotarohara** [comment] 2016-09-08 19:29
Ok, can you continue it? I'll look into more detail. I get the feeling that the timeout length is overwritten by the default value (30 min) somewhere.

**Comment by kotarohara** [comment] 2016-09-09 19:09
I looked into this yesterday and checked when the session times out. It seems like timeout is properly set to 30 days, so I'm not sure why it is still forcing you to log out... @manaswis , are you sure you are using the right branch `login-session-timeout`?

**Comment by manaswis** [comment] 2016-09-09 19:15
Okay. I will do another test now using the branch. I think when I git pulled it, it received some commits with logout comments and assumed it was added to the branch I was using.

I will post my results after a few hours of testing.

**Comment by manaswis** [comment] 2016-09-10 01:16
Its working! Yay! :)

<img width="1277" alt="sign_out_solved" src="https://cloud.githubusercontent.com/assets/2873216/18406944/af3480c4-76d2-11e6-8e4c-0e8c924f09be.png">

**Comment by kotarohara** [comment] 2016-09-12 16:32
Ok. I merged this into the master.

**Closed by kotarohara** 2016-09-12 16:32 UTC
Labels: bug
