### ISSUE TITLE
Cursor should switch to open hand when cursor is in GSV pane in validation interface

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1544] opened 2019-03-09 14:16 UTC
Cursor should switch to open hand when cursor is in GSV pane in validation interface

![image](https://user-images.githubusercontent.com/1621749/54072651-bdb40380-4232-11e9-85da-76f6e7764e62.png)

**Comment by misaugstad** [comment] 2019-03-11 19:14
duplicate of #1393

**Closed by misaugstad** 2019-03-11 19:14 UTC
Labels: EasyFix!, Validation
