### ISSUE TITLE
Need to add crosswalk and pedestrian signal to the interactive tutorial

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3029] opened 2022-09-15 21:57 UTC
Crosswalk labels here:
![image](https://user-images.githubusercontent.com/1621749/190514001-80c82bde-8ca1-45e5-94ee-8956bd224f75.png)

This is a pedestrian signal (there doesn't appear to be a push button but still clearly shows a pedestrian signal with countdown):
![image](https://user-images.githubusercontent.com/1621749/190514226-8268f628-7714-4fbc-b9d3-9cdc680bb51d.png)

There is another crosswalk here:
![image](https://user-images.githubusercontent.com/1621749/190514438-084e6911-ef44-4695-808d-712bbbc8b243.png)

Finally, we'll likely want to indicate the presence of this crosswalk and pedestrian signal after we highlight the lack of curb ramps (for completeness). 
![image](https://user-images.githubusercontent.com/1621749/190515782-86045e8d-65ac-4352-bad2-5c6e4dea3ec6.png)

Relatedly, I think after the user says "Yes, I see the missing curb ramps", we might want to then show the "missing curb ramp" labels show up in the right place. Similarly, when we point out the crosswalk and pedestrian signal, we can do the same thing. Like perhaps at this point, the labels show up:
![image](https://user-images.githubusercontent.com/1621749/190515928-d4299f6f-bf60-40c7-a279-e62eac7999e9.png)

**Comment by misaugstad** [comment] 2022-09-16 21:10
@jonfroehlich do you have any ideas on what we can take out of the tutorial? We've already talked about how the tutorial is really long, and this definitely adds a ton to it! Or maybe we just let it be a bit longer, since users really do need more training, and we'd rather have slightly fewer users if it means that they are better trained at this point?

**Comment by jonfroehlich** [comment] 2022-09-16 21:41
I thought of this too. Very good point!

But here's the thing: just as you allude to, we are switching to a model where we don't necessarily care if the tutorial is longer as long as its length is commensurate with good training information and user education. I'm no longer concerned with random users dropping out because the tutorial is too long (which yes, definitely happens!) and, instead, would prefer that only those users who are relatively well-informed do the auditing.

We are also, generally, as a project shifting to working with more invested partners: government workers, community organizations, high school students doing service hours, college classrooms, etc. So, I think better training is inline with that. 

I'm also writing the v2 of our Labeling Guide with the same philosophy. We might publish an abbreviated summary version of the guide but we'll largely be pointing people to the full Labeling Guide when we do our mapathons and other collaborations.

**Comment by jonfroehlich** [comment] 2023-05-10 12:46
I'm preparing for a talk this morning and went through the whole tutorial. Just flagging that this is still a problem.

It doesn't "feel right" for the tutorial to completely ignore two other label types when clearly those elements need to be considered and labeled in the streetscape imagery.

Here's a full recording of the current tutorial. I again suggest that the solution is for us to add these labels to the tutorial (which will of course lengthen it). Relatedly, I think the tutorial may need to end with a sort of quiz that checks knowledge and even may ask about common labeling mistakes (e.g., is a driveway a curb ramp?)

https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/09e42b2e-94bd-4dde-9b86-6c3e6d5e3973

**Comment by jonfroehlich** [comment] 2023-07-17 13:19
I think we need to fix this before @crescendochu runs her CHI study. As now, I'm thinking that we will not offer our user study participants additional training outside of the interactive tutorial (to maintain ecological validity with a field deployment scenario). 

Thoughts @crescendochu?

**Comment by crescendochu** [comment] 2023-07-17 13:41
Yes we are not offering our user study participants additional training outside of the interactive tutorial but we do not have crosswalk and pedestrian signal in our model, currently it is just the five major label types.

**Comment by jonfroehlich** [comment] 2023-07-17 13:44
Ah, gotcha. Then we need not prioritize this for your study (but we should still address this for the upcoming deployments in Burnaby, Teaneck, etc.)

**Comment by misaugstad** [comment] 2023-10-19 21:07
closing as a duplicate of #2846

**Closed by misaugstad** 2023-10-19 21:07 UTC
Labels: Tutorial
