### ISSUE TITLE
Bug In Using Keyboard For Labeling

### ISSUE THREAD

**Issue by Soben713** [ProjectSidewalk/SidewalkWebpage#213] opened 2016-08-16 21:19 UTC
When using keyboard numbers to specify a label's significance (passable/not passable) the corresponding radio-button gets selected but it is not saved. I'm using Chrome v52.

**Comment by jonfroehlich** [comment] 2016-08-17 12:49
This is a duplicate of https://github.com/ProjectSidewalk/SidewalkWebpage/issues/197.

I believe it was fixed. I'll let @kotarohara comment and close if it is.

**Comment by jonfroehlich** [comment] 2016-08-22 13:53
@kotarohara, is this now fixed?

**Comment by kotarohara** [comment] 2016-08-22 15:23
Yes, this is fixed.

**Closed by kotarohara** 2016-08-22 15:23 UTC
Labels: bug
