### ISSUE TITLE
Need to add crosswalks and pedestrian signals

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2914] opened 2022-05-24 16:25 UTC
For the validation study (and beyond), it would be nice to have crosswalks and pedestrian signals in admin:

![image](https://user-images.githubusercontent.com/1621749/170084520-3a344388-e6ed-4a19-a497-5b35357a0222.png)

**Comment by misaugstad** [comment] 2022-05-24 20:58
duplicate of #2896

**Closed by misaugstad** 2022-05-24 20:58 UTC
Labels: Admin Interface
