### ISSUE TITLE
Surveys should show questions that are relevant to the user group (admin, turker, researcher,...)

### ISSUE THREAD

**Issue by maddalihanumateja** [ProjectSidewalk/SidewalkWebpage#1077] opened 2017-09-11 20:50 UTC
As discussed in #1031 the survey should adapt itself to display questions relevant to the user groups. There is already a user_role attribute for the questions that we can use for this in the control logic for surveys.

**Comment by misaugstad** [comment] 2018-08-11 19:27
Copying over some info from the thread on giving the survey to volunteers ( #1136 ).

These are how the questions are worded for turkers right now:
1. "How much did you enjoy this task?"
2. "How difficult did you find this task?"
3. "How well do you think you did on this task?"
4. "Why did you choose to contribute to Project Sidewalk?"
5. "Do you have any feedback for us?"

@jonfroehlich has suggested rewording the questions in this way for volunteers:
1. "How much have you been enjoying using Project Sidewalk?"
2. "How easy or difficult is it to use Project Sidewalk?"
3. "How well do you think you are performing on the labeling tasks?"
4. "Why did you choose to contribute to Project Sidewalk?" (no change)
5. "Do you have any feedback, design ideas, or questions?"

I think that some of those changes could be used for both turkers and volunteers (like changing "Do you have any feedback for us?" to "Do you have any feedback, design ideas, or questions?").

**Comment by misaugstad** [comment] 2018-08-30 05:08
>however, it would be nice if our backend code were written to support different survey questions--not sure how hard that would be; if hard, don't do it!

Luckily, it already is! (thanks Teja!)

>Let's change Question 5 to "Do you have any feedback, design ideas, or questions for us" because it seems more personal and demonstrates our agency to the user (that is, that we are actually people behind the system!).

Agreed.

**Comment by misaugstad** [comment] 2019-01-24 21:07
We decided to keep the survey the same across user groups, though the way this was designed, we can always change this if we change our mind later. Closing since we decided it is better to keep the survey the same across user groups.

**Closed by misaugstad** 2019-01-24 21:07 UTC
Labels: NextCity, in progress
