### ISSUE TITLE
New Admin Map Interface: Labels Not Showing Correctly

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#527] opened 2017-03-12 18:07 UTC
I just quickly tested @m-furman's new interactive admin map interface. It's definitely far more responsive (though still not fluidly interactive) and a big improvement over the past interface. 

However, I noticed that some labels do not appear to show up correctly when you interact with the checkboxes. For example, we supposedly have over 10,000 No Sidewalk labels, however, when I deselect everything but this label type, I only see a handful of No Sidewalk labels:

![image](https://cloud.githubusercontent.com/assets/1621749/23834433/e3e1bea0-072c-11e7-961f-a9320af50233.png)

Similar problem for Can't See Sidewalk where no labels are shown:
![image](https://cloud.githubusercontent.com/assets/1621749/23834439/0448358e-072d-11e7-8e69-e3edb8071d5a.png)

Perhaps this problem affects *all* label types but is only most noticeable for the above.

**Comment by misaugstad** [comment] 2018-09-07 18:07
Here is a video Jon took of him testing this. Originally posted in issue #1150 (which I closed as a duplicate).
[https://youtu.be/N5buE-SqwZU](https://youtu.be/N5buE-SqwZU)

**Comment by misaugstad** [comment] 2018-09-07 18:10
I took a look at this, and the issue is that we are only showing labels that have a severity rating. Since NoSidewalk and Occlusion don't have severity ratings (except for those couple NoSidewalk that have a rating from the first couple days when the tool was launched), none of those labels are showing. This also means that labels from other label types where users did not mark severity are not being shown. Should be an easy fix (if it doesn't results in more data than the browser can handle).

**Comment by jonfroehlich** [comment] 2018-09-07 19:01
Great, thanks. We just need some screenshots for the paper atm (so it doesn't even need to be interactive but it does not to show all the labels for each label type). See: https://github.com/jonfroehlich/ProjectSidewalkCHI2019/issues/1

**Comment by misaugstad** [comment] 2018-09-07 19:12
It does cause the program to crash because we run out of heap space. I am temporarily solving so that I can get screenshots by running `export SBT_OPTS="-Xmx4G"` in the terminal where I call `sbt run`, but I haven't figured out how to set that option within the project. I tried modifying the `javaOptions` variable in `build.sbt`, but that didn't change anything.

**Comment by misaugstad** [comment] 2019-05-20 17:08
Hey @annieyx how do you feel about taking up this issue? To find this webpage you will need to create an account on your local database, then modify the `user_role` table in the database to have the "Administrator" role. Once you've done that, when you click on your username on the top-right of the webpage, you should see an "admin" option so you can navigate to the admin page. Then you can click on the "map" tab and it should show you the map above.

The relevant code should be in public/javascripts/SVLabel/src/Admin/Admin.js.

**Comment by jonfroehlich** [comment] 2019-06-17 20:28
Ultimately, I think the sliders themselves should be *range* *sliders* where you have two thumbs on each slider--one to set the min value (inclusive) and one to set the max value (inclusive). Some sample codes here:

- http://jqueryui.com/slider/#range
- https://github.com/Wildhoney/ngRangeSlider
- https://codepen.io/Pierre_Hamel/pen/ocJEH

**Comment by misaugstad** [comment] 2019-07-24 18:38
closing via #1816

**Closed by misaugstad** 2019-07-24 18:38 UTC
Labels: Admin Interface, EasyFix!, Priority: Low, bug
